XBar.Lng = {
	["Ttip"]={
		["CfgBtn1"]="XBar Configuration",
		["CfgBtn2"]="Left-Click to open the configuration.\nRight-Click to open the addons menu.\nMiddle-Click to toggles Autorun.",
		["SysBtn1"]="System Function",
		["SysBtn2"]="Left-Click to open the main menu.\nRight-Click to open the system menu.\nMiddle-Click to execute ReloadUI().",
		["DspBtn1"]="Left-Click to open the Transport Book.\nRight-Click toggles the Large Map.\nMiddle-Click set display to low quality.",
		["SndBtn1"]="Left-Click to open the World Search.\nRight-Click to open Instance Progress.\nMiddle-Click to mute all sounds.",

		["Ammo1"]="Left-Click to open Quest Log.\nRight-Click to open Monster Compendium.",

		["Bag1"]="Left-Click to open Backpack.\nRight-Click to preview Bank or open Portable Bank.",

		["Class1"]="Left-Click to open CharacterFrame.\nRight-Click to open Item-Set Skills.\nMiddle-Click to open the TitleFrame.\nCtrl + Right-Click to remove title.",

		["Clock1"]="Left-Click to switch 12H or 24H format.\nRight-Click to switch Time or Date.\nShift-Click to switch session or total time.",
		["Clock2"]="Online Total",

		["Craft1"]="Craft",
		["Craft2"]="Left-Click to open Arcane Transmutor.\nRight-Click to open Rune Extraction.",
		["Craft3"]="Last / Repeat",
		["Craft4"]="Count",

		["Dps1"]="DPS / Dura / Ability",
		["Dps2"]="Left-Click to open the durability frame.\nRight-Click to swap equipment.",

		["Exp1"]="XP / TP",
		["Exp2"]="Left-Click to open Skill Book.\nRight-Click to open CraftFrame.",
		["Exp3"]="Current",
		["Exp4"]="Needed",
		["Exp5"]="Last",
		["Exp6"]="Repeats",
		["Exp7"]="TP Current",

		["Friend1"]="Left-Click to interact with online friends.\nRight-Click to open the SocialFrame.",
		["Friend2"]="Friends online",
		["Friend3"]="Group :",

		["Guild1"]="Left-Click to interact with online member.\nRight-Click to open the GuildFrame.",
		["Guild2"]="Member",

		["Appointment"]="Unregistered",
		["Failed"]="No Opponent",
		["Disable"]="|cffFFAA00Not Started|r",
		["Prepare"]="|cffFFAA00Preparing|r",
		["Fight"]="|cffFFAA00Fighting (Didn't enter)|r",
		["Fighting"]="|cffFFAA00Fighting (Entered)|r",
		["FightEnd"]="Finished",

		["Mail1"]="Mail / Sold items in Auction",
		["Mail2"]="Left-Click to open the Postbox.\nRight-Click to open the Partner Bag.",
		["Mail3"]="Sold",

		["Money1"]="Left-Click to open the Item Shop Bagpack.\nRight-Click to open the Item Shop.",
		["Money2"]="Earned",
		["Money3"]="Spent",
		["Money4"]="Balance",

		["Ping1"]="Performance",
		["Ping2"]="Left-Click to open the Transport Book.",
		["Ping3"]="Right-Click to open the World Search.",

		["EQDmg1"]="Change Text",
		["EQDmg2"]="- Use this frame to rapair or change equipment.\n- |cffFFAA00Left-Click|r to use Repair Hammer which shows in most right if you have.",
		["AvgDur"]="Average Durability",
		["LowDur"]="Lowest Durability",

		["CR_REST"]="Ctrl + Right-Click to reset ",
		["LMOUSE_WSP"]="Left-Click to whisper.",
		["RMOUSE_INV"]="Right-Click invites to party.",
		["SCROLL_ON"]="Scrollthrough enabled.",
		["Loc"]="Location :",
		["Note"]="Note :",
		["Sys_SC1"]="Character Selection",

		["Bon_Bu1"]="Macro-Commands help",
		["Bon_Bu2"]="Open browser",
		["Bon_Bu3"]="ThreatMeter in party",
		["Bon_Bu4"]="Target Preview",
		["Bon_Bu5"]="Call/Recall slot3 pet",
		["Bon_Bu6"]="Call/Recall slot2 pet",
		["Bon_Bu7"]="Call/Recall slot1 pet",
		["Bon_Bu8"]="Switch weapons",
		["Bon_Bu9"]="Save Raid",
		["Bon_Bu10"]="Save and leave Raid",
		["Bon_Bu11"]="Invite Raid",
		["Bon_Bu12"]="Save and reload Raid",
	},
	["Config"]={
		["saved"]="|cffFFE855XBar|r config saved.",
		["help"]="XBar Help:",
		["toggle_xbar"]="|cffFFE855/xb on|r - toggle XBar background.",
		["toggle_main"]="|cffFFE855/xb main|r - toggles the MainMenuFrame.",
		["toggle_expf"]="|cffFFE855/xb exp|r - toggles the ExperienceFrame.",
		["loaded1"]="|cffFFE855XBar [EN] ",
		["loaded2"]="|r loaded, type |cffFFE855/xbar|r to config.",
		["Title"]="XBar Addon Management System",
		["Descr"]="nigrangelus: I wrote this once to just enhance the XBar's configurability.\nIts able to let any addon be a part of itself, so there is no need to have various windows opened.",
		["Info"]="Shift + Right-click to move buttons on XBar.\nMouse Wheel on ChatFrame to scroll.\nYou can delete button files which you don't need.\nAfter you delete buttons please restart the game.",
		["EnableXBar"]="Enable XBar",
		["Top"]="On Top",
		["Bottom"]="On Bottom",
		["Main4"]="Show all main buttons",
		["Main2"]="Show 2 main buttons",
		["Main0"]="Hide all main buttons",
		["Style"]="Style",
		["HideOriginalXP"]="Hide original Experience Frame",
		["HideOriginalED"]="Hide original EquipDamage Frame",
		["Text1"]="Textfield 1",
		["Text2"]="Textfield 2",
		["Value"]="Content (limited to 255 chars)",
		["ValueL1"]="Content A: (limited to 255 chars) |cffFFE855[L-Click]|r",
		["ValueL2"]="Content B: (limited to 255 chars) |cffFFE855[L-Click]|r",
		["ValueR"]="Content C: (limited to 255 chars) |cffFFE855[R-Click]|r",
		["ValueSL1"]="Content A: (ltd. to 255 chars) |cffFFE855[Shift + L-Click]|r",
		["ValueSL2"]="Content B: (ltd. to 255 chars) |cffFFE855[Shift + L-Click]|r",
		["Head"]="|cffFFE855Keywords Replace|r\n\n",

		["Count"]="%s Count",
		["Name"]="%s Name",

		["Bag1"]="%s Used Slots",
		["Bag2"]="Total slots in Backpack",
		["Bag3"]="Used percent of %s",

		["Class1"]="Third Class",
		["Class2"]="%s Level",
		["Class3"]="Finished Quests",

		["Clock1"]="Online Time",
		["Clock2"]="Total Online Time",

		["Craft1"]="%s Lv",
		["Craft2"]="%s XP",
		["Craft3"]="The times %s need to repeat to next Lv",
		["Craft4"]="Last %s XP",

		["Dps1"]="%s Per Second",
		["Dps2"]="Last %s",
		["Dps3"]="Killed Monsters",

		["Exp1"]="Needed XP to level up",
		["Exp2"]="Max XP for this level",
		["Exp3"]="XP in %",
		["Exp4"]="Needed XP in %",
		["Exp5"]="Repeats till lvl up",
		["Exp6"]="Last %s gained",
		["Exp7"]="%s gained this session",
		["Exp8"]="TP Total",
		["Exp9"]="TP Used",
		["Exp10"]="Bonus %s",
		["Exp11"]="%s Debt",
		["Exp12"]="%s XP",
		["Exp13"]="%s Max XP",

		["Friend1"]="Friends Online Count",
		["Friend2"]="Friends Total Count",

		["Guild1"]="Members Online Count",
		["Guild2"]="Total Member",
		["Guild3"]="Max member at guild's lvl",

		["Mail1"]="Received Mails",
	},
	["X3"]={
		["AngelSwitch"]="XBar: Weapons-Switch finished.",
		["InParty"]="vcThreatMeter show only in party.",
		["InCombat"]="vcThreatMeter show in combat.",
		["Msg1"]="XBar Available Commands (macro or chat)",
		["Msg2"]="|cffFFE855/run XBar.heal()|r : target and heal people whose hp is lowest.",
		["Msg3"]="|cffFFE855/run XBar.rogue()|r : Rogue skill-rotation, checks debuffs, cooldowns & energy then use corresponding skill.",
		["Msg4"]="|cffFFE855/run XBar.party()|r : traget party member 1~5 sequentially.",
		["Msg5"]="|cffFFE855/run XBar.switch()|r : switch weapons to other equipt.",
		["Msg6"]="|cffFFE855/run XBar.strip()|r : unequipt all items to 2nd bag or equipt all items.",
		["Msg7"]="|cffFFE855/run XBar.pet1()|r : call/recall slot1 pet.",
		["Msg8"]="|cffFFE855/run XBar.pet2()|r : call/recall slot2 pet.",
		["Msg9"]="|cffFFE855/run XBar.pet3()|r : call/recall slot3 pet.",
		["Msg10"]="|cffFFE855/run XBar.preview()|r : Target Preview.",
	},
	["XM"]={
		["Anchor"]="Show Anchor",
		["Size"]="Absolute Size :",
		["Style"]="Style",
		["Switch"]="Quick Switch",
		["Zone"]="Zone Name",
		["Time"]="Map Time",
		["Coord"]="Coordinate",
		["Tab1"]="Minimap",
		["Tab2"]="Buttons",
		["Left"]="Left-Click to toggle Minimap.",
		["Right"]="Right-Click to open Minimap buttons menu.",
		["Middle"]="Middle-Click to toggle Worldmap.",
		["Saved"]="config saved.",
		["Load"]="loaded, type",
		["ToConfig"]="to config.",
	},
	["SDL"]={
		["In"] = "Damage In",
		["Out"] = "Damage Out",
		["AddOnDescription"] = "Shows incoming and outgoing damage and heals in small movable text areas.",
		["Enable"] = "Enable Add-on",
		["IncomingDamage"] = "Show Incoming Damage",
		["IncomingHeals"] = "Show Incoming Heals",
		["Loaded"] = "loaded",
		["Lock"] = "Lock Frame Positions",
		["OutgoingDamage"] = "Show Outgoing Damage",
		["OutgoingHeals"] = "Show Outgoing Heals",
		["ShowDamageSource"] = "Show Damage Source",
		["ShowHealSource"] = "Show Healing Source",
	},
}