XBar.Lng = {
	["Ttip"]={
		["CfgBtn1"]="Opciones de XBar",
		["CfgBtn2"]="Boton izquiero para abrir el menu de configuracion.\nBoton derecho para abrir el menu addons.\nMiddle-Click to toggles Autorun.",
		["SysBtn1"]="Funciones del sistema",
		["SysBtn2"]="Boton izquierdo para abrir el menu principal.\nBoton derecho para abrir el menu del sistema.\nMiddle-Click para recargar la interfaz ReloadUI().",
		["DspBtn1"]="Boton izquierdo para abrir el libro de teletransporte.\nBoton derecho oculta/muestra el mapa del mundo.\nMiddle-Click set display to low quality.",
		["SndBtn1"]="Boton izquierdo to open the World Search.\nRight-Click to open Instance Progress.\nBoton medio para silenciar todo.",

		["Ammo1"]="Left-Click to open Quest Log.\nRight-Click to open Monster Compendium.",

		["Bag1"]="Boton izquierdo para abrir la mochila.\nRight-Click to preview Bank or open Portable Bank.",

		["Class1"]="Boton izquierdo para abrir la ventana de Personaje.\nBoton derecho para abrir la lista de Item-Set Skills.\nBoton medio para abrir la lista de Titulos.\nCtrl + Right-Click to remove title.",

		["Clock1"]="Boton izquiero para cambiar entre 12H y 24H.\nBoton derecho para cambiar entre Hora y Fecha.\nMayusculas-izquierdo para cambiar entre tiempo de la sesion y tiempo total de juego.",
		["Clock2"]="Total jugado",

		["Craft1"]="Craft",
		["Craft2"]="Left-Click to open Arcane Transmutor.\nRight-Click to open Rune Extraction.",
		["Craft3"]="Last / Repeat",
		["Craft4"]="Count",

		["Dps1"]="Daño / Durabilidad",
		["Dps2"]="Boton izquierdo para abrir la ventana de durabilidad\nRight-Click to swap equipment.",

		["Exp1"]="Experiencia / Deuda / Capacidad",
		["Exp2"]="Boton izquierdo para abrir la ventana de habilidades.\nBoton derecho para abrir la ventana de Artesania.",
		["Exp3"]="actual",
		["Exp4"]="necesaria",
		["Exp5"]="ultimo",
		["Exp6"]="repetir",
		["Exp7"]="TP Current",

		["Friend1"]="Boton izquierdo para interactuar con amigos conectados.\nBoton derecho para abrir la ventana de Social.",
		["Friend2"]="amigos online",
		["Friend3"]="grupo:",

		["Guild1"]="Boton izquierdo pra interactuar con los miembros conectados.\nBoton derecho para abrir la ventana de Gremio.",
		["Guild2"]="miembro",

		["Appointment"]="No Registrado",
		["Failed"]="Sin Rival",
		["Disable"]="|cffFFAA00No Disponible|r",
		["Prepare"]="|cffFFAA00Preparación|r",
		["Fight"]="|cffFFAA00Luchar (No entrar)|r",
		["Fighting"]="|cffFFAA00Luchar (Mención)|r",
		["FightEnd"]="Acabado",

		["Mail1"]="Correo / Sold items in Auction",
		["Mail2"]="Boton izquierdo para abrir el buzon.\nBoton derecho para abrir la PartnerFrame.",
		["Mail3"]="Sold",

		["Money1"]="Boton izquierdo para abrir la mochila de la tienda.\nBoton derecho para abrir la Item Shop.",
		["Money2"]="ganado",
		["Money3"]="gastado",
		["Money4"]="balance",

		["Ping1"]="Rendimiento",
		["Ping2"]="Boton izquierdo para abrir el libro de teletransporte.",
		["Ping3"]="Right-Click to open the World Search.",

		["EQDmg1"]="Change Text",
		["EQDmg2"]="- Use this frame to rapair or change equipment.\n- |cffFFAA00Left-Click|r to use Repair Hammer which shows in most right if you have.",
		["AvgDur"]="Durabilidad media",
		["LowDur"]="Durability menor",

		["CR_REST"]="Ctrl + Right-Click to reset ",
		["LMOUSE_WSP"]="Boton izquierdo para susurrar.",
		["RMOUSE_INV"]="Boton derecho para invitar al grupo.",
		["SCROLL_ON"]="Scroll activado.",
		["Loc"]="Zona :",
		["Note"]="Nota :",
		["Sys_SC1"]="Cambiar de Personaje",

		["Bon_Bu1"]="Ayuda de macros",
		["Bon_Bu2"]="open browser",
		["Bon_Bu3"]="ThreatMeter in party",
		["Bon_Bu4"]="Vista del objetivo",
		["Bon_Bu5"]="Call/Recall slot3 pet",
		["Bon_Bu6"]="Call/Recall slot2 pet",
		["Bon_Bu7"]="Call/Recall slot1 pet",
		["Bon_Bu8"]="Switch weapons",
		["Bon_Bu9"]="Guardar grupo",
		["Bon_Bu10"]="Guardar y dejar grupo",
		["Bon_Bu11"]="Invitar al grupo",
		["Bon_Bu12"]="Save and reload Raid",
	},
	["Config"]={
		["saved"]="|cffFFE855XBar|r configuracion guardada.",
		["help"]="XBar Ayuda:",
		["toggle_xbar"]="|cffFFE855/xb on|r - oculta/muestra la barra de XBar",
		["toggle_main"]="|cffFFE855/xb main|r - oculta/muestra el menu principal",
		["toggle_expf"]="|cffFFE855/xb exp|r - oculta/muestra la barra de experiencia",
		["loaded1"]="|cffFFE855XBar [ES] ",
		["loaded2"]="|r cargado, tipo |cffFFE855/xbar|r para configurar.",
		["Title"]="XBar Addon Sistema de Gestion",
		["Descr"]="nigrangelus: Yo programe esta herramienta simplemente para mejorar XBar. Cualquier addon puede integrarse en ella.",
		["Info"]="Shift + Right-click to move buttons on XBar.\nMouse Wheel on ChatFrame to scroll.\nYou can delete button files which you don't need.\nAfter you delete buttons please restart game.",
		["EnableXBar"]="Activar xBar",
		["Top"]="Arriba",
		["Bottom"]="Abajo",
		["Main4"]="Mostrar todo la buttons principal",
		["Main2"]="Mostrar 2 la buttons principal",
		["Main0"]="Oculta todo la buttons principal",
		["Style"]="Estilo",
		["HideOriginalXP"]="Oculta la barra de experiencia",
		["HideOriginalED"]="Oculta la ventana de durabilidad",
		["Text1"]="Campo de texto 1",
		["Text2"]="Campo de texto 2",
		["Value"]="Contenido (limite 255 chars)",
		["ValueL1"]="Contenido A: (limitado a 255 chars) |cffFFE855[boton-izq|r",
		["ValueL2"]="Contenido B: (limitado a 255 chars) |cffFFE855[boton-izq]|r",
		["ValueR"]="Contenido C: (limitado a 255 chars) |cffFFE855[boton-dcho]|r",
		["ValueSL1"]="Contenido A: (lim. 255 chars) |cffFFE855[Mayus + boton-izq]|r",
		["ValueSL2"]="Contenido B: (lim. 255 chars) |cffFFE855[Mayus + boton-izq]|r",
		["Head"]="|cffFFE855Palabras Sustituidas|r\n\n",

		["Count"]="Recuento %s",
		["Name"]="Nombre %s",

		["Bag1"]="%s utiliza ranuras",
		["Bag2"]="Total de las ranuras de la bolsa",
		["Bag3"]="Uso de la %s como porcentaje",

		["Class1"]="Clase tercero",
		["Class2"]="Nivel de la %s",
		["Class3"]="Finished Quests",

		["Clock1"]="Duracion de esta sesion",
		["Clock2"]="Total de tiempo jugando",

		["Craft1"]="%s Lv",
		["Craft2"]="%s XP",
		["Craft3"]="The times %s need to repeat to next Lv",
		["Craft4"]="Última %s XP",

		["Dps1"]="%s por segundo",
		["Dps2"]="Ultimo %s",
		["Dps3"]="Monstruos muertos",

		["Exp1"]="XP para el siguiente lvl",
		["Exp2"]="Max de XP para este nivel",
		["Exp3"]="XP actual en %",
		["Exp4"]="XP necesaria en %",
		["Exp5"]="Repeticiones hasta el siguiente nivel",
		["Exp6"]="Ultimo %s ganados",
		["Exp7"]="%s ganados esta sesion",
		["Exp8"]="TP total",
		["Exp9"]="TP utilizado",
		["Exp10"]="bonus %s",
		["Exp11"]="Dedua %s",
		["Exp12"]="%s XP",
		["Exp13"]="%s max XP",

		["Friend1"]="Numero de amigos conectados",
		["Friend2"]="Numero total de amigos",

		["Guild1"]="Numero de miembros conectados",
		["Guild2"]="Numero total de miembros",
		["Guild3"]="Max de miembros del gremio",

		["Mail1"]="Numero de correos",
	},
	["X3"]={
		["AngelSwitch"]="XBar: Cambio de armamento realizado.",
		["InParty"]="vcThreatMeter show only in party.",
		["InCombat"]="vcThreatMeter show in combat.",
		["Msg1"]="XBar Comandos disponibles (macro o chat)",
		["Msg2"]="|cffFFE855/run XBar.heal()|r : busca el PJ con menos vida dentro del grupo o area",
		["Msg3"]="|cffFFE855/run XBar.rogue()|r : Rogue skill-rotation, checks debuffs, cooldowns & energy then use corresponding skill.",
		["Msg4"]="|cffFFE855/run XBar.party()|r : traget party member 1~5 sequentially.",
		["Msg5"]="|cffFFE855/run XBar.switch()|r : intercambia las armar por las del otro equipo",
		["Msg6"]="|cffFFE855/run XBar.strip()|r : desnuda el PJ dejando todo en la 2 pagina de la mochila",
		["Msg7"]="|cffFFE855/run XBar.pet1()|r : call/recall slot1 pet.",
		["Msg8"]="|cffFFE855/run XBar.pet2()|r : call/recall slot2 pet.",
		["Msg9"]="|cffFFE855/run XBar.pet3()|r : call/recall slot3 pet.",
		["Msg10"]="|cffFFE855/run XBar.preview()|r : Target Preview.",
	},
	["XM"]={
		["Anchor"]="Mostar esquina",
		["Size"]="Tama�o absoluto :",
		["Style"]="Estilo",
		["Switch"]="Cambio r�pido",
		["Zone"]="Nombre Zona",
		["Time"]="Reloj del mapa",
		["Coord"]="Coordinar",
		["Tab1"]="Minimapa",
		["Tab2"]="Botones",
		["Left"]="Boton izquierdo oculta/muestra el minimapa.",
		["Right"]="Right-Click to open Minimap buttons menu.",
		["Middle"]="Boton derecho oculta/muestra el mapa del mundo.",
		["Saved"]="configuracion guardada.",
		["Load"]="cargado, tipo",
		["ToConfig"]="para configurar.",
	},
	["SDL"]={
		["In"] = "Daños En",
		["Out"] = "Daños Salida",
		["AddOnDescription"] = "Despliega el da\195\177o causado y recibido por el jugador in peque\195\177as regiones movibles.",
		["Enable"] = "Habilitar add-on",
		["IncomingDamage"] = "Deplegar da\195\177o entrante",
		["IncomingHeals"] = "Deplegar curas entrantes",
		["Loaded"] = "cargado",
		["Lock"] = "Bloquear movimiento de pantallas",
		["OutgoingDamage"] = "Deplegar da\195\177o saliente",
		["OutgoingHeals"] = "Deplegar curas salientes",
		["ShowDamageSource"] = "Desplegar qui\195\169n te hace da\195\177o",
		["ShowHealSource"] = "Desplegar qui\195\169n te cura",
	},
}