XBar.Lng = {
	["Ttip"]={
		["CfgBtn1"]="Configation XBar",
		["CfgBtn2"]="Click-Gauche pour ouvrir le menu de configuration.\nClick-Droit pour ouvrir le menu addons.\nMiddle-Click to toggles Autorun.",
		["SysBtn1"]="Fonctions Syst\195\168me.",
		["SysBtn2"]="Click-Gauche pour ouvrir le menu principal.\nClick-Droit pour ouvrir le menu syst\195\168me.\nMiddle-Click pour ex\195\169cuter ReloadUI().",
		["DspBtn1"]="Click-Gauche pour ouvrir le livre des transports.\nClick-Droit toggles la Carte du monde.\nMiddle-Click set display to low quality.",
		["SndBtn1"]="Click-Gauche pour open the World Search.\nRight-Click to open Instance Progress.\nClick-Moyen pour couper tous les sons.",

		["Ammo1"]="Left-Click to open Quest Log.\nRight-Click to open Monster Compendium.",

		["Bag1"]="Click-Gauche pour ouvrir le sac \195\160 dos.\nRight-Click to preview Bank or open Portable Bank.",

		["Class1"]="Click-Gauche pour ouvrir panneau du joueur.\nClick-Droit pour ouvrir livre des Item-Set Skills.\nClick-Moyen pour ouvrir livre des titres.\nCtrl + Right-Click to remove title.",

		["Clock1"]="Click-Gauche pour passer du format 12H vers 24h.\nClick-Droit pour afficher Heure ou Date.\nShift-Click pour afficher session or temps total.",
		["Clock2"]="Total jou\195\169",

		["Craft1"]="Craft",
		["Craft2"]="Left-Click to open Arcane Transmutor.\nRight-Click to open Rune Extraction.",
		["Craft3"]="Last / Repeat",
		["Craft4"]="Count",

		["Dps1"]="DPS / Durabilit\195\169 / Capacité",
		["Dps2"]="Click-Gauche pour ouvrir la fen\195\170tre de durabilit\195\169.\nRight-Click to swap equipment.",

		["Exp1"]="Exp\195\169rience / Dette",
		["Exp2"]="Click-Gauche pour ouvrir livre des comp\195\169tences.\nClick-Droit pour ouvrir fen\195\170 de production.",
		["Exp3"]="Courant",
		["Exp4"]="N\195\169cessaire",
		["Exp5"]="Dernier",
		["Exp6"]="R\195\169p\195\169ter",
		["Exp7"]="TP Current",

		["Friend1"]="Click-Gauche pour interagir avec les amis en ligne.\nClick-Droit pour ouvrir Liste d'amis.",
		["Friend2"]="Amis en ligne",
		["Friend3"]="Groupe :",

		["Guild1"]="Click-Gauche pour interagir avec les membres en ligne.\nClick-Droit pour ouvrir PanneauGuilde.",
		["Guild2"]="Membre",

		["Appointment"]="Non Enregistré",
		["Failed"]="Aucun opposant",
		["Disable"]="|cffFFAA00Non disponible|r",
		["Prepare"]="|cffFFAA00Préparation|r",
		["Fight"]="|cffFFAA00Combattre (N'a pas entrer)|r",
		["Fighting"]="|cffFFAA00Combattre (Entrée)|r",
		["FightEnd"]="Terminé",

		["Mail1"]="Courrier / Sold items in Auction",
		["Mail2"]="Click-Gauche pour ouvrir votre bo\195\175te de courrier.\nClick-Droit pour ouvrir PartnerFrame.",
		["Mail3"]="Sold",

		["Money1"]="Click-Gauche pour ouvrir le Sac \195\160 dos boutique.\nClick-Droit pour ouvrir Item Shop.",
		["Money2"]="Gagn\195\169",
		["Money3"]="D\195\169pens\195\169",
		["Money4"]="Balance",

		["Ping1"]="Performance",
		["Ping2"]="Click-Gauche pour ouvrir le livre des transports.",
		["Ping3"]="Right-Click to open the World Search.",

		["EQDmg1"]="Change Text",
		["EQDmg2"]="- Use this frame to rapair or change equipment.\n- |cffFFAA00Left-Click|r to use Repair Hammer which shows in most right if you have.",
		["AvgDur"]="Durabilit\195\169 moyenne",
		["LowDur"]="Durabilit\195\169 le plus bas",

		["CR_REST"]="Ctrl + Right-Click to reset ",
		["LMOUSE_WSP"]="Click-Gauche pour murmurer.",
		["RMOUSE_INV"]="Click-Droit inviter dans le groupe.",
		["SCROLL_ON"]="D\195\169filement activ\195\169.",
		["Loc"]="Location :",
		["Note"]="Note :",
		["Sys_SC1"]="Ecran s\195\169lection du perso.",

		["Bon_Bu1"]="Macro-Commands help",
		["Bon_Bu2"]="Ouvrir navigateur",
		["Bon_Bu3"]="ThreatMeter in party",
		["Bon_Bu4"]="Target Preview",
		["Bon_Bu5"]="Call/Recall familier slot3",
		["Bon_Bu6"]="Call/Recall familier slot2",
		["Bon_Bu7"]="Call/Recall familier slot1",
		["Bon_Bu8"]="Switch weapons",
		["Bon_Bu9"]="Sauvegarder Groupe",
		["Bon_Bu10"]="Sauvegarder et laisser Groupe",
		["Bon_Bu11"]="Inviter dans Groupe",
		["Bon_Bu12"]="Save and reload Raid",
	},
	["Config"]={
		["saved"]="Configation |cffFFE855XBar|r sauvegard\195\169.",
		["help"]="Aide XBar:",
		["toggle_xbar"]="|cffFFE855/xb on|r - toggle XBar arri\195\168re-plan.",
		["toggle_main"]="|cffFFE855/xb main|r - toggles le panneau du menu principal",
		["toggle_expf"]="|cffFFE855/xb exp|r - toggles la panneau d'Exp\195\169rience",
		["loaded1"]="|cffFFE855XBar [FR] ",
		["loaded2"]="|r chargés, tapez |cffFFE855/xbar|r pour configurer",
		["Title"]="XBar Addon Management System",
		["Descr"]="nigrangelus: J'ai \195\169crit ceci pour am\195\169liorer la configuration XBar's.\nPermer de g\195\169rer tous les addons en m\195\170me temps dans une seule fen\195\170tre.",
		["Info"]="Shift + Right-click to move buttons on XBar.\nMouse Wheel on ChatFrame to scroll.\nYou can delete button files which you don't need.\nAfter you delete buttons please restart game.",
		["EnableXBar"]="XBar Activ\195\169",
		["Top"]="En Haut",
		["Bottom"]="En Bas",
		["Main4"]="Montrer tous les boutons principaux",
		["Main2"]="Montrer 2 les boutons principaux",
		["Main0"]="Cacher tous les boutons principaux",
		["Style"]="Style",
		["HideOriginalXP"]="Cacher cadre original Exp\195\169rience",
		["HideOriginalED"]="Cacher cadre original EquipDommage",
		["Text1"]="ChampTexte 1",
		["Text2"]="ChampTexte 2",
		["Value"]="Contenu (limit\195\169 \195\160 255 chars.)",
		["ValueL1"]="Contenu A: (limit\195\169 \195\160 255 chars) |cffFFE855[L-Click]|r",
		["ValueL2"]="Contenu B: (limit\195\169 \195\160 255 chars) |cffFFE855[L-Click]|r",
		["ValueR"]="Contenu C: (limit\195\169 \195\160 255 chars) |cffFFE855[R-Click]|r",
		["ValueSL1"]="Contenu A: (ltd. \195\160 255 chars) |cffFFE855[Shift + L-Click]|r",
		["ValueSL2"]="Contenu B: (ltd. \195\160 255 chars) |cffFFE855[Shift + L-Click]|r",
		["Head"]="|cffFFE855Mots Remplacés|r\n\n",

		["Count"]="Comptage des %s",
		["Name"]="Nom de %s",

		["Bag1"]="%s de slots utilisés",
		["Bag2"]="Max. de slots dispo. dans votre sac",
		["Bag3"]="Affiche le pct d'utilisation de %s",

		["Class1"]="ClasseTroisième",
		["Class2"]="Niveau de la %s",
		["Class3"]="Finished Quests",

		["Clock1"]="Temps en ligne cette session",
		["Clock2"]="Temps en ligne total",

		["Craft1"]="%s Lv",
		["Craft2"]="%s XP",
		["Craft3"]="The times %s need to repeat to next Lv",
		["Craft4"]="Dernière %s XP",

		["Dps1"]="%s \195\169valu\195\169 par seconde",
		["Dps2"]="Dernier %s",
		["Dps3"]="Mobs Tu\195\169s",

		["Exp1"]="PEX n\195\169cessaire pour niv",
		["Exp2"]="Max PEX pour ce niveau",
		["Exp3"]="PEX actuel en %",
		["Exp4"]="PEX n\195\169cessaire en %",
		["Exp5"]="R\195\169p\195\170ter till lvl up",
		["Exp6"]="Dernier %s gagné",
		["Exp7"]="%s gagn\195\169 cette session",
		["Exp8"]="TP totale",
		["Exp9"]="TP utilisée",
		["Exp10"]="Bonusmaison %s",
		["Exp11"]="Dette %s",
		["Exp12"]="%s PEX",
		["Exp13"]="%s max PEX",

		["Friend1"]="Nombre d'amis en ligne",
		["Friend2"]="Nombre d'amis total",

		["Guild1"]="Nbr de Membres en ligne",
		["Guild2"]="Total membre",
		["Guild3"]="Max membre de guilde niv",

		["Mail1"]="Courrier reçu",
	},
	["X3"]={
		["AngelSwitch"]="XBar: Changement-Arme termin\195\169.",
		["InParty"]="vcThreatMeter show only in party.",
		["InCombat"]="vcThreatMeter show in combat.",
		["Msg1"]="XBar Commandes disponibles (macro ou chat)",
		["Msg2"]="|cffFFE855/run XBar.heal()|r : target et heal les gens les plus souffrant.",
		["Msg3"]="|cffFFE855/run XBar.rogue()|r : Rogue skill-rotation, checks debuffs, cooldowns & energy then use corresponding skill.",
		["Msg4"]="|cffFFE855/run XBar.party()|r : traget party member 1~5 sequentially.",
		["Msg5"]="|cffFFE855/run XBar.switch()|r : switch weapons to other equipt.",
		["Msg6"]="|cffFFE855/run XBar.strip()|r : unequipt all items to 2nd bag or equipt all items.",
		["Msg7"]="|cffFFE855/run XBar.pet1()|r : call/recall familier slot1.",
		["Msg8"]="|cffFFE855/run XBar.pet2()|r : call/recall familier slot2.",
		["Msg9"]="|cffFFE855/run XBar.pet3()|r : call/recall familier slot3.",
		["Msg10"]="|cffFFE855/run XBar.preview()|r : Target Preview.",
	},
	["XM"]={
		["Anchor"]="Montrer Encrage",
		["Size"]="Taille absolu :",
		["Style"]="Style",
		["Switch"]="Commutateur rapide",
		["Zone"]="Nom Zone",
		["Time"]="HeureCarte",
		["Coord"]="Coordonner",
		["Tab1"]="Mini-Carte",
		["Tab2"]="Boutons",
		["Left"]="Click-Gauche toggles la Minicarte.",
		["Right"]="Right-Click to open Minimap buttons menu.",
		["Middle"]="Click-milieu toggles la Carte du monde.",
		["Saved"]="configation sauvegard\195\169.",
		["Load"]="chargés, tapez",
		["ToConfig"]="pour configurer",
	},
	["SDL"]={
		["In"] = "Damage In",
		["Out"] = "Damage Out",
		["AddOnDescription"] = "Shows incoming and outgoing damage and heals in small movable text areas.",
		["Enable"] = "Enable Add-on",
		["IncomingDamage"] = "Show Incoming Damage",
		["IncomingHeals"] = "Show Incoming Heals",
		["Loaded"] = "loaded",
		["Lock"] = "Lock Frame Positions",
		["OutgoingDamage"] = "Show Outgoing Damage",
		["OutgoingHeals"] = "Show Outgoing Heals",
		["ShowDamageSource"] = "Show Damage Source",
		["ShowHealSource"] = "Show Healing Source",
	},
}