XBar.Lng = {
	["Ttip"]={
		["CfgBtn1"]="XBar 設定画面",
		["CfgBtn2"]="左クリックで設定メニューを開く.\n右クリックでアドオンメニューを開く.\nホイールクリックで自動前進.",
		["SysBtn1"]="システム機能",
		["SysBtn2"]="左クリックでメインメニューを開く.\n右クリックでシステムメニューを開く.\n中クリックで ReloadUI() 実行.",
		["DspBtn1"]="左クリックでワープスクロールを開く.\n右クリックでワールドマップを切り替えます.\n中クリックで画質を低いに設定する.",
		["SndBtn1"]="左クリックでワールド検索を開く.\nRight-Click to open Instance Progress.\n中クリックで全てのサウンドをミュート.",

		["Ammo1"]="左クリックでクエスト欄を開く.\n右クリックでカードリストを開く.",

		["Bag1"]="左クリックで鞄を開く.\n右クリックで銀行を開く or open Portable Bank.",

		["Class1"]="左クリックでキャラクターウィンドウを開く.\n右クリックでスーツスキルウィンドウを開く.\n中クリックで称号ウィンドウを開く.\nCtrl + 右クリックで称号を外す.",

		["Clock1"]="左クリックで12/24時間形式を切り替え.\n右クリックで時刻/日付を切り替え.\nShift + クリックでセッション/合計時間を切り替え.",
		["Clock2"]="プレイ合計",

		["Craft1"]="採集",
		["Craft2"]="左クリックでマジックボックスを開く.\n右クリックでルーン抽出を開く.",
		["Craft3"]="Last / Repeat",
		["Craft4"]="Count",

		["Dps1"]="DPS / 耐久度 / ステータス",
		["Dps2"]="左クリックで耐久度フレーム表示.\n右クリックで装備交換.",

		["Exp1"]="XP / TP",
		["Exp2"]="左クリックでスキルブックを開く.\n右クリックで生産画面を開く.",
		["Exp3"]="現在",
		["Exp4"]="必要",
		["Exp5"]="前回",
		["Exp6"]="必要回数",
		["Exp7"]="現在のTP",

		["Friend1"]="左クリックでオンラインのフレンドと会話.\n右クリックでフレンドリストを開く.",
		["Friend2"]="オンライン数",
		["Friend3"]="グループ :",

		["Guild1"]="左クリックでオンラインメンバーと対話.\n右クリックでギルドウィンドウを開く.",
		["Guild2"]="メンバー",

		["Appointment"]="未登録",
		["Failed"]="いいえ対戦相手いない",
		["Disable"]="|cffFFAA00使用できない|r",
		["Prepare"]="|cffFFAA00準備|r",
		["Fight"]="|cffFFAA00バトル（入力されていません）|r",
		["Fighting"]="|cffFFAA00バトル（入力）|r",
		["FightEnd"]="完成した",

		["Mail1"]="メール / 競売で売却したアイテム",
		["Mail2"]="左クリックでポストを開く.\n右クリックでPartnerFrameウィンドウを開く.",
		["Mail3"]="売却",

		["Money1"]="左クリックで有料アイテムウィンドウを開く\n右クリックでショッピングウィンドウを開く.",
		["Money2"]="獲得",
		["Money3"]="消費",
		["Money4"]="バランス",

		["Ping1"]="パフォーマンス",
		["Ping2"]="左クリックでワープスクロールを開く.",
		["Ping3"]="右クリックでワールド検索を開く.",

		["EQDmg1"]="表示切り替え",
		["EQDmg2"]="- Use this frame to rapair or change equipment.\n- |cffFFAA00Left-Click|r to use Repair Hammer which shows in most right if you have.",
		["AvgDur"]="平均耐久度",
		["LowDur"]="最低耐久度",

		["CR_REST"]="Ctrl+右クリックでリセット",
		["LMOUSE_WSP"]="左クリックでささやき.",
		["RMOUSE_INV"]="右クリックでパーティーに招待.",
		["SCROLL_ON"]="スクロール有効.",
		["Loc"]="所在地 :",
		["Note"]="ノート :",
		["Sys_SC1"]="キャラクターセレクト",

		["Bon_Bu1"]="Macro-Commands help",
		["Bon_Bu2"]="Open browser",
		["Bon_Bu3"]="ThreatMeter in party",
		["Bon_Bu4"]="Target Preview",
		["Bon_Bu5"]="Call/Recall slot3 pet",
		["Bon_Bu6"]="Call/Recall slot2 pet",
		["Bon_Bu7"]="Call/Recall slot1 pet",
		["Bon_Bu8"]="Switch weapons",
		["Bon_Bu9"]="Save Raid",
		["Bon_Bu10"]="Save and leave Raid",
		["Bon_Bu11"]="Invite Raid",
		["Bon_Bu12"]="Save and reload Raid",
	},
	["Config"]={
		["saved"]="|cffFFE855XBar|r 設定を保存しました.",
		["help"]="XBar Help:",
		["toggle_xbar"]="|cffFFE855/xb on|r - XBarの背景をトグル.",
		["toggle_main"]="|cffFFE855/xb main|r - メインメニューフレームをトグル.",
		["toggle_expf"]="|cffFFE855/xb exp|r - 経験値フレームをトグル.",
		["loaded1"]="|cffFFE855XBar [JP] ",
		["loaded2"]="|r 読み込みました, 入力 |cffFFE855/xbar|r 設定メニューを開く.",
		["Title"]="XBar アドオン管理システム",
		["Descr"]="私はカスタマイズ性を高める為に、Xbarを作成しました.\nXbar一つで色々な機能を兼ね備えている為\nデフォルトのウインドウを開く必要がありません.",
		["Info"]="Shift + Right-click to move buttons on XBar.\nMouse Wheel on ChatFrame to scroll.\nYou can delete button files which you don't need.\nAfter you delete buttons please restart game.",
		["EnableXBar"]="XBar を有効",
		["Top"]="最上部",
		["Bottom"]="最下部",
		["Main4"]="全てのメインボタンを示す",
		["Main2"]="二つのメインボタンを示す",
		["Main0"]="全てのメインボタンを隠す",
		["Style"]="スタイル",
		["HideOriginalXP"]="標準経験値フレームを隠す",
		["HideOriginalED"]="標準装備破損フレームを隠す",
		["Text1"]="テキスト欄 1",
		["Text2"]="テキスト欄 2",
		["Value"]="コンテンツ (255文字まで)",
		["ValueL1"]="内容 A: (255文字まで) |cffFFE855[L-Click]|r",
		["ValueL2"]="内容 B: (255文字まで) |cffFFE855[L-Click]|r",
		["ValueR"]="内容 C: (255文字まで) |cffFFE855[R-Click]|r",
		["ValueSL1"]="内容 A: (255文字まで) |cffFFE855[Shift + L-Click]|r",
		["ValueSL2"]="内容 B: (255文字まで) |cffFFE855[Shift + L-Click]|r",
		["Head"]="|cffFFE855キーワード置き換え|r\n\n",

		["Count"]="%sの所持数",
		["Name"]="%sの名前",

		["Bag1"]="%sの使用スロット数",
		["Bag2"]="鞄の最大スロット数",
		["Bag3"]="%sの占有している割合",

		["Class1"]="第三のクラス",
		["Class2"]="%sLV",
		["Class3"]="未完了クエスト数",

		["Clock1"]="このセッションのオンライン時間",
		["Clock2"]="オンライン時間全体",

		["Craft1"]="%sLv",
		["Craft2"]="%sXP",
		["Craft3"]="次のレベルアップまでに必要な回数（%s）",
		["Craft4"]="最後に%sした時の経験値",

		["Dps1"]="毎秒あたりの%s",
		["Dps2"]="前回%s",
		["Dps3"]="モンスター殺傷数",

		["Exp1"]="必要経験値",
		["Exp2"]="このLVの最大経験値",
		["Exp3"]="実際の経験値の%",
		["Exp4"]="必要経験値の%",
		["Exp5"]="LVアップまでの繰り返し数",
		["Exp6"]="前回の%s",
		["Exp7"]="このセッションで得た%s",
		["Exp8"]="総獲得TP",
		["Exp9"]="使用済TP",
		["Exp10"]="%sハウスボーナス",
		["Exp11"]="%sペナルティ",
		["Exp12"]="%sの経験値",
		["Exp13"]="%sの最大経験値",

		["Friend1"]="オンラインフレンド数",
		["Friend2"]="登録フレンド数",

		["Guild1"]="オンラインメンバー数",
		["Guild2"]="メンバー総数",
		["Guild3"]="ギルドレベルでの最大のメンバー数",

		["Mail1"]="受信メール数",
	},
	["X3"]={
		["AngelSwitch"]="XBar: Weapons-Switch finished.",
		["InParty"]="vcThreatMeter show only in party.",
		["InCombat"]="vcThreatMeter show in combat.",
		["Msg1"]="XBar Available Commands (macro or chat)",
		["Msg2"]="|cffFFE855/run XBar.heal()|r : target and heal people whose hp is lowest.",
		["Msg3"]="|cffFFE855/run XBar.rogue()|r : Rogue skill-rotation, checks debuffs, cooldowns & energy then use corresponding skill.",
		["Msg4"]="|cffFFE855/run XBar.party()|r : traget party member 1~5 sequentially.",
		["Msg5"]="|cffFFE855/run XBar.switch()|r : switch weapons to other equipt.",
		["Msg6"]="|cffFFE855/run XBar.strip()|r : unequipt all items to 2nd bag or equipt all items.",
		["Msg7"]="|cffFFE855/run XBar.pet1()|r : call/recall slot1 pet.",
		["Msg8"]="|cffFFE855/run XBar.pet2()|r : call/recall slot2 pet.",
		["Msg9"]="|cffFFE855/run XBar.pet3()|r : call/recall slot3 pet.",
		["Msg10"]="|cffFFE855/run XBar.preview()|r : Target Preview.",
	},
	["XM"]={
		["Anchor"]="アンカー表示",
		["Size"]="実寸 :",
		["Style"]="スタイル",
		["Switch"]="クイックスイッチ",
		["Zone"]="ゾーン名",
		["Time"]="マップ時間",
		["Coord"]="座標",
		["Tab1"]="ミニマップ",
		["Tab2"]="ボタン",
		["Left"]="左クリックでミニマップを切り替えます.",
		["Right"]="Right-Click to open Minimap buttons menu.",
		["Middle"]="中クリックでワールドマップを切り替えます.",
		["Saved"]="設定を保存しました.",
		["Load"]="読み込みました, 入力",
		["ToConfig"]="設定メニューを開く.",
	},
	["SDL"]={
		["In"] = "Damage In",
		["Out"] = "Damage Out",
		["AddOnDescription"] = "Shows incoming and outgoing damage and heals in small movable text areas.",
		["Enable"] = "Enable Add-on",
		["IncomingDamage"] = "Show Incoming Damage",
		["IncomingHeals"] = "Show Incoming Heals",
		["Loaded"] = "loaded",
		["Lock"] = "Lock Frame Positions",
		["OutgoingDamage"] = "Show Outgoing Damage",
		["OutgoingHeals"] = "Show Outgoing Heals",
		["ShowDamageSource"] = "Show Damage Source",
		["ShowHealSource"] = "Show Healing Source",
	},
}