XBar.Lng = {
	["Ttip"]={
		["CfgBtn1"] = "XBar 구성",
		["CfgBtn2"] = "설정 메뉴를 열려면 마우스 왼쪽 클릭\nRight-Click to open the addons menu.\nMiddle-Click to toggles Autorun.",
		["SysBtn1"] = "시스템 기능",
		["SysBtn2"] = "메인 메뉴를 열려면 마우스 왼쪽 클릭\n시스템 메뉴를 열려면 마우스 오른쪽 클릭\nUI 재설정(화면 리로드)하려면 마우스 Middle-Click",
		["DspBtn1"] = "순간이동 룬 화면을 열려면 마우스 왼쪽 클릭\n월드맵은 마우스 오른쪽 클릭\nMiddle-Click set display to low quality.",
		["SndBtn1"] = "Right-Click to open the World Search.\nRight-Click to open Instance Progress.\n모든 소리를 없애려면 마우스 가운데 단추",

		["Ammo1"]="Left-Click to open Quest Log.\nRight-Click to open Monster Compendium.",

		["Bag1"] = "소지품 가방을 열려면 마우스 왼쪽 클릭\nRight-Click to preview Bank or open Portable Bank.",

		["Class1"] = "캐릭터 화면을 열려면 마우스 왼쪽 클릭 \nItem-Set Skills 화면을 열려면 마우스 오른쪽 클릭\n타이틀 화면을 열려면 마우스 가운데 클릭\nCtrl + Right-Click to remove title.",

		["Clock1"] = "12시간 또는 24시간 표시는 마우스 왼쪽 클릭\n시간이나 날짜 표시는 마우스 오른쪽 클릭\n전체 시간으로 바꾸려면 Shift + 마우스 왼쪽 클릭",
		["Clock2"] = "전체 플레이 시간",

		["Craft1"]="Craft",
		["Craft2"]="Left-Click to open Arcane Transmutor.\nRight-Click to open Rune Extraction.",
		["Craft3"]="Last / Repeat",
		["Craft4"]="Count",

		["Dps1"] = "DPS/내구도/능력",
		["Dps2"] = "내구도 화면을 열려면 마우스 왼쪽 클릭\nRight-Click to swap equipment.",

		["Exp1"] = "경험치 / TP",
		["Exp2"] = "스킬북을 열려면 마우스 왼쪽 클릭 \n생산창을 열려면 마우스 오른쪽 클릭",
		["Exp3"] = "현재",
		["Exp4"] = "필요",
		["Exp5"] = "마지막",
		["Exp6"] = "반복",
		["Exp7"]="TP Current",

		["Friend1"] = "접속 중인 친구는 마우스 왼쪽 클릭 \n친구목록을 열려면 마우스 오른쪽 클릭",
		["Friend2"] = "접속 중인 친구",
		["Friend3"] = "그룹 :",

		["Guild1"] = "접속중인 길드원은 마우스 왼쪽 클릭 \n길드 화면을 열려면 마우스 오른쪽 클릭",
		["Guild2"] = "멤버",

		["Appointment"]="등록되지 않은",
		["Failed"]="어떤 상대가 없습니다",
		["Disable"]="|cffFFAA00사용할 수 없음|r",
		["Prepare"]="|cffFFAA00준비|r",
		["Fight"]="|cffFFAA00파이팅 (입력하지 않았습니다)|r",
		["Fighting"]="|cffFFAA00파이팅 (체결)|r",
		["FightEnd"]="완성",

		["Mail1"] = "편지 / Sold items in Auction",
		["Mail2"] = "우편함을 열려면 마우스 왼쪽 클릭\nRight-Click to open the Partner Bag.",
		["Mail3"]="Sold",

		["Money1"] = "아이템 몰 가방을 열려면 마우스 왼쪽 클릭\nRight-Click to open the Item Shop.",
		["Money2"] = "수입",
		["Money3"] = "지출",
		["Money4"] = "균형",

		["Ping1"] = "성능",
		["Ping2"] = "순간이동 룬 화면을 열려면 마우스 왼쪽 클릭",
		["Ping3"]="Right-Click to open the World Search.",

		["EQDmg1"]="Change Text",
		["EQDmg2"]="- Use this frame to rapair or change equipment.\n- |cffFFAA00Left-Click|r to use Repair Hammer which shows in most right if you have.",
		["AvgDur"] = "평균 내구도", -- Needs review
		["LowDur"]="가장 내구도",

		["CR_REST"]="Ctrl + Right-Click to reset ",
		["LMOUSE_WSP"] = "귓속말을 하려면 마우스 왼쪽 클릭",
		["RMOUSE_INV"] = "파티 초대를 하려면 오른쪽 클릭",
		["SCROLL_ON"] = "스크롤 기능 사용",
		["Loc"] = "위치 : ",
		["Note"] = "요약 :",
		["Sys_SC1"]="Character Selection",

		["Bon_Bu1"]="Macro-Commands help",
		["Bon_Bu2"]="Open browser",
		["Bon_Bu3"]="ThreatMeter in party",
		["Bon_Bu4"]="Target Preview",
		["Bon_Bu5"]="Call/Recall slot3 pet",
		["Bon_Bu6"]="Call/Recall slot2 pet",
		["Bon_Bu7"]="Call/Recall slot1 pet",
		["Bon_Bu8"]="Switch weapons",
		["Bon_Bu9"]="Save Raid",
		["Bon_Bu10"]="Save and leave Raid",
		["Bon_Bu11"]="Invite Raid",
		["Bon_Bu12"]="Save and reload Raid",
	},
	["Config"]={
		["saved"] = "|cffFFE855XBar|r 설정이 저장되었습니다.",
		["help"] = "XBar 도움말 :",
		["toggle_xbar"] = "|cffFFE855/xb on|r - XBar 화면 표시 on/off 토글",
		["toggle_main"] = "|cffFFE855/xb main|r - XBar 메인메뉴 화면 on/off 토글",
		["toggle_expf"] = "|cffFFE855/xb exp|r - 경험치 바 on/off 토글",
		["loaded1"] = "|cffFFE855XBar [KR] ",
		["loaded2"] = "|r 로드됨, 설정 메뉴를 열려면 입력 |cffFFE855/xbar|r.",
		["Title"]="XBar Addon Management System",
		["Descr"]="nigrangelus: I wrote this once to just enhance the XBar's configurability.\nIts able to let any addon be a part of itself, so there is no need to have various windows opened.",
		["Info"]="Shift + Right-click to move buttons on XBar.\nMouse Wheel on ChatFrame to scroll.\nYou can delete button files which you don't need.\nAfter you delete buttons please restart game.",
		["EnableXBar"]="Enable XBar",
		["Top"]="On Top",
		["Bottom"]="On Bottom",
		["Main4"]="Show all main buttons",
		["Main2"]="Show 2 main buttons",
		["Main0"]="Hide all main buttons",
		["Style"]="Style",
		["HideOriginalXP"]="Hide original Experience Frame",
		["HideOriginalED"]="Hide original EquipDamage Frame",
		["Text1"]="Textfield 1",
		["Text2"]="Textfield 2",
		["Value"]="Content (limited to 255 chars)",
		["ValueL1"]="Content A: (limited to 255 chars) |cffFFE855[L-Click]|r",
		["ValueL2"]="Content B: (limited to 255 chars) |cffFFE855[L-Click]|r",
		["ValueR"]="Content C: (limited to 255 chars) |cffFFE855[R-Click]|r",
		["ValueSL1"]="Content A: (ltd. to 255 chars) |cffFFE855[Shift + L-Click]|r",
		["ValueSL2"]="Content B: (ltd. to 255 chars) |cffFFE855[Shift + L-Click]|r",
		["Head"]="|cffFFE855Keywords Replace|r\n\n",

		["Count"]="%s Count",
		["Name"]="%s Name",

		["Bag1"]="%s Used Slots",
		["Bag2"]="Total slots in Backpack",
		["Bag3"]="Used percent of %s",

		["Class1"]="Third Class",
		["Class2"]="%s Level",
		["Class3"]="Finished Quests",

		["Clock1"]="Online Time",
		["Clock2"]="Total Online Time",

		["Craft1"]="%s Lv",
		["Craft2"]="%s XP",
		["Craft3"]="The times %s need to repeat to next Lv",
		["Craft4"]="Last %s XP",

		["Dps1"]="%s Per Second",
		["Dps2"]="Last %s",
		["Dps3"]="Killed Monsters",

		["Exp1"]="Needed XP to level up",
		["Exp2"]="Max XP for this level",
		["Exp3"]="XP in %",
		["Exp4"]="Needed XP in %",
		["Exp5"]="Repeats till lvl up",
		["Exp6"]="Last %s gained",
		["Exp7"]="%s gained this session",
		["Exp8"]="TP Total",
		["Exp9"]="TP Used",
		["Exp10"]="Bonus %s",
		["Exp11"]="%s Debt",
		["Exp12"]="%s XP",
		["Exp13"]="%s Max XP",

		["Friend1"]="Friends Online Count",
		["Friend2"]="Friends Total Count",

		["Guild1"]="Members Online Count",
		["Guild2"]="Total Member",
		["Guild3"]="Max member at guild's lvl",

		["Mail1"]="Received Mails",
	},
	["X3"]={
		["AngelSwitch"]="XBar: Weapons-Switch finished.",
		["InParty"]="vcThreatMeter show only in party.",
		["InCombat"]="vcThreatMeter show in combat.",
		["Msg1"]="XBar Available Commands (macro or chat)",
		["Msg2"]="|cffFFE855/run XBar.heal()|r : target and heal people whose hp is lowest.",
		["Msg3"]="|cffFFE855/run XBar.rogue()|r : Rogue skill-rotation, checks debuffs, cooldowns & energy then use corresponding skill.",
		["Msg4"]="|cffFFE855/run XBar.party()|r : traget party member 1~5 sequentially.",
		["Msg5"]="|cffFFE855/run XBar.switch()|r : switch weapons to other equipt.",
		["Msg6"]="|cffFFE855/run XBar.strip()|r : unequipt all items to 2nd bag or equipt all items.",
		["Msg7"]="|cffFFE855/run XBar.pet1()|r : call/recall slot1 pet.",
		["Msg8"]="|cffFFE855/run XBar.pet2()|r : call/recall slot2 pet.",
		["Msg9"]="|cffFFE855/run XBar.pet3()|r : call/recall slot3 pet.",
		["Msg10"]="|cffFFE855/run XBar.preview()|r : Target Preview.",
	},
	["XM"]={
		["Anchor"]="Show Anchor",
		["Size"]="Absolute Size :",
		["Style"]="Style",
		["Switch"]="Quick Switch",
		["Zone"]="Zone Name",
		["Time"]="Map Time",
		["Coord"]="Coordinate",
		["Tab1"]="Minimap",
		["Tab2"]="Buttons",
		["Left"]="Left-Click toggles the Minimap.",
		["Right"]="Right-Click to open Minimap buttons menu.",
		["Middle"]="Middle-Click to toggle Worldmap.",
		["Saved"]="config saved.",
		["Load"]="loaded, type",
		["ToConfig"]="to config.",
	},
	["SDL"]={
		["In"] = "Damage In",
		["Out"] = "Damage Out",
		["AddOnDescription"] = "Shows incoming and outgoing damage and heals in small movable text areas.",
		["Enable"] = "Enable Add-on",
		["IncomingDamage"] = "Show Incoming Damage",
		["IncomingHeals"] = "Show Incoming Heals",
		["Loaded"] = "loaded",
		["Lock"] = "Lock Frame Positions",
		["OutgoingDamage"] = "Show Outgoing Damage",
		["OutgoingHeals"] = "Show Outgoing Heals",
		["ShowDamageSource"] = "Show Damage Source",
		["ShowHealSource"] = "Show Healing Source",
	},
}