XBar.Lng = {
	["Ttip"]={
		["CfgBtn1"] = "Конфигурация XBar",
		["CfgBtn2"] = "Левый клик открывает меню конфигурации\nRight-Click to open the addons menu.\nMiddle-Click to toggles Autorun.",
		["SysBtn1"] = "Системная функция",
		["SysBtn2"] = "Левый клик для открытия главного меню\nПравый клик открывает системное меню\nMiddle-Click перезагрузит интерфейс",
		["DspBtn1"] = "Левый клик откроет книгу перемещений\nПравый клик включает Большую карту\nMiddle-Click set display to low quality.",
		["SndBtn1"] = "Левый клик open the World Search.\nRight-Click to open Instance Progress.\nБлижний клик выключает весь звук",

		["Ammo1"]="Left-Click to open Quest Log.\nRight-Click to open Monster Compendium.",

		["Bag1"] = "Левый клик откроет рюкзак\nRight-Click to preview Bank or open Portable Bank.",

		["Class1"] = "Левый клик откроет окно игрока.\nПравый клик откроет окно Item-Set Skills.\nБлижний клик откроет окно званий.\nCtrl + Right-Click to remove title.",

		["Clock1"] = "Левый клик переключает между 12 и 24 форматами времени\nПравый клик переключает между датой и временем\nShift+ левый клик переключает между общим временем и временем сессии.",
		["Clock2"] = "Всего",

		["Craft1"]="Craft",
		["Craft2"]="Left-Click to open Arcane Transmutor.\nRight-Click to open Rune Extraction.",
		["Craft3"]="Last / Repeat",
		["Craft4"]="Count",

		["Dps1"] = "Прочность",
		["Dps2"] = "Левый клик открывает окно с прочностью вещей\nRight-Click to swap equipment.",

		["Exp1"] = "Опыт",
		["Exp2"] = "Левый клик открывает книгу скиллов.\nПравый клик открывает книгу крафта",
		["Exp3"] = "Имеется",
		["Exp4"] = "Необходимо",
		["Exp5"] = "Последний",
		["Exp6"] = "Повторы",
		["Exp7"]="TP Current",

		["Friend1"] = "Левый клик прошептать другу.\nПравый клик открывает социальное окно.",
		["Friend2"] = "Друзей онлайн",
		["Friend3"] = "Группа:",

		["Guild1"] = "Левый клик прошептать согильдийцу.\nПравый клик открывает окно гильдии.",
		["Guild2"] = "член",

		["Appointment"]="Незарегистрированный",
		["Failed"]="Нет Противник",
		["Disable"]="|cffFFAA00Нет в наличии|r",
		["Prepare"]="|cffFFAA00Подготовка|r",
		["Fight"]="|cffFFAA00Борьба (Еще не входят)|r",
		["Fighting"]="|cffFFAA00Борьба (Вступил)|r",
		["FightEnd"]="Законченный",

		["Mail1"] = "Почта / Sold items in Auction",
		["Mail2"] = "Левый клик открывает почту.\nRight-Click to open the Partner Bag.",
		["Mail3"]="Sold",

		["Money1"] = "Левый клик открывает рюкзак магазина.\nRight-Click to open the Item Shop.",
		["Money2"] = "получено",
		["Money3"] = "потрачено",
		["Money4"] = "баланс",

		["Ping1"] = "На месте",
		["Ping2"] = "Левый клик откроет книгу перемещений",
		["Ping3"]="Right-Click to open the World Search.",

		["EQDmg1"]="Change Text",
		["EQDmg2"]="- Use this frame to rapair or change equipment.\n- |cffFFAA00Left-Click|r to use Repair Hammer which shows in most right if you have.",
		["AvgDur"] = "Средняя прочность",
		["LowDur"]="Самая низкая Прочность",

		["CR_REST"]="Ctrl + Right-Click to reset ",
		["LMOUSE_WSP"] = "Кликните левой мышью для шепота",
		["RMOUSE_INV"] = "Кликните правой мышью чтобы пригласить в группу",
		["SCROLL_ON"] = "Прокрутка включена",
		["Loc"] = "Локация:",
		["Note"] = "Запись:",
		["Sys_SC1"]="Character Selection",

		["Bon_Bu1"]="Macro-Commands help",
		["Bon_Bu2"]="Open browser",
		["Bon_Bu3"]="ThreatMeter in party",
		["Bon_Bu4"]="Target Preview",
		["Bon_Bu5"]="Call/Recall slot3 pet",
		["Bon_Bu6"]="Call/Recall slot2 pet",
		["Bon_Bu7"]="Call/Recall slot1 pet",
		["Bon_Bu8"]="Switch weapons",
		["Bon_Bu9"]="Save Raid",
		["Bon_Bu10"]="Save and leave Raid",
		["Bon_Bu11"]="Invite Raid",
		["Bon_Bu12"]="Save and reload Raid",
	},
	["Config"]={
		["saved"] = "Конфигурация |cffFFE855XBar|r сохранена.",
		["help"] = "XBar помощь:",
		["toggle_xbar"] = "|cffFFE855/xb on|r - переключатели XBarFrame's Display", -- Needs review
		["toggle_main"] = "|cffFFE855/xb main|r - переключатели Главного меню",
		["toggle_expf"] = "|cffFFE855/xb exp|r - переключатели панели опыта",
		["loaded1"] = "|cffFFE855XBar [RU] ",
		["loaded2"] = "r загружен, вводить |cffFFE855/xbar|r открывает меню конфигурации.",
		["Title"]="XBar Addon Management System",
		["Descr"]="nigrangelus: I wrote this once to just enhance the XBar's configurability.\nIts able to let any addon be a part of itself, so there is no need to have various windows opened.",
		["Info"]="Shift + Right-click to move buttons on XBar.\nMouse Wheel on ChatFrame to scroll.\nYou can delete button files which you don't need.\nAfter you delete buttons please restart game.",
		["EnableXBar"]="Enable XBar",
		["Top"]="On Top",
		["Bottom"]="On Bottom",
		["Main4"]="Show all main buttons",
		["Main2"]="Show 2 main buttons",
		["Main0"]="Hide all main buttons",
		["Style"]="Style",
		["HideOriginalXP"]="Hide original Experience Frame",
		["HideOriginalED"]="Hide original EquipDamage Frame",
		["Text1"]="Textfield 1",
		["Text2"]="Textfield 2",
		["Value"]="Content (limited to 255 chars)",
		["ValueL1"]="Content A: (limited to 255 chars) |cffFFE855[L-Click]|r",
		["ValueL2"]="Content B: (limited to 255 chars) |cffFFE855[L-Click]|r",
		["ValueR"]="Content C: (limited to 255 chars) |cffFFE855[R-Click]|r",
		["ValueSL1"]="Content A: (ltd. to 255 chars) |cffFFE855[Shift + L-Click]|r",
		["ValueSL2"]="Content B: (ltd. to 255 chars) |cffFFE855[Shift + L-Click]|r",
		["Head"]="|cffFFE855Keywords Replace|r\n\n",

		["Count"]="%s Count",
		["Name"]="%s Name",

		["Bag1"]="%s Used Slots",
		["Bag2"]="Total slots in Backpack",
		["Bag3"]="Used percent of %s",

		["Class1"]="Third Class",
		["Class2"]="%s Level",
		["Class3"]="Finished Quests",

		["Clock1"]="Online Time",
		["Clock2"]="Total Online Time",

		["Craft1"]="%s Lv",
		["Craft2"]="%s XP",
		["Craft3"]="The times %s need to repeat to next Lv",
		["Craft4"]="Last %s XP",

		["Dps1"]="%s Per Second",
		["Dps2"]="Last %s",
		["Dps3"]="Killed Monsters",

		["Exp1"]="Needed XP to level up",
		["Exp2"]="Max XP for this level",
		["Exp3"]="XP in %",
		["Exp4"]="Needed XP in %",
		["Exp5"]="Repeats till lvl up",
		["Exp6"]="Last %s gained",
		["Exp7"]="%s gained this session",
		["Exp8"]="TP Total",
		["Exp9"]="TP Used",
		["Exp10"]="Bonus %s",
		["Exp11"]="%s Debt",
		["Exp12"]="%s XP",
		["Exp13"]="%s Max XP",

		["Friend1"]="Friends Online Count",
		["Friend2"]="Friends Total Count",

		["Guild1"]="Members Online Count",
		["Guild2"]="Total Member",
		["Guild3"]="Max member at guild's lvl",

		["Mail1"]="Received Mails",
	},
	["X3"]={
		["AngelSwitch"]="XBar: Weapons-Switch finished.",
		["InParty"]="vcThreatMeter show only in party.",
		["InCombat"]="vcThreatMeter show in combat.",
		["Msg1"]="XBar Available Commands (macro or chat)",
		["Msg2"]="|cffFFE855/run XBar.heal()|r : target and heal people whose hp is lowest.",
		["Msg3"]="|cffFFE855/run XBar.rogue()|r : Rogue skill-rotation, checks debuffs, cooldowns & energy then use corresponding skill.",
		["Msg4"]="|cffFFE855/run XBar.party()|r : traget party member 1~5 sequentially.",
		["Msg5"]="|cffFFE855/run XBar.switch()|r : switch weapons to other equipt.",
		["Msg6"]="|cffFFE855/run XBar.strip()|r : unequipt all items to 2nd bag or equipt all items.",
		["Msg7"]="|cffFFE855/run XBar.pet1()|r : call/recall slot1 pet.",
		["Msg8"]="|cffFFE855/run XBar.pet2()|r : call/recall slot2 pet.",
		["Msg9"]="|cffFFE855/run XBar.pet3()|r : call/recall slot3 pet.",
		["Msg10"]="|cffFFE855/run XBar.preview()|r : Target Preview.",
	},
	["XM"]={
		["Anchor"]="Show Anchor",
		["Size"]="Absolute Size :",
		["Style"]="Style",
		["Switch"]="Quick Switch",
		["Zone"]="Zone Name",
		["Time"]="Map Time",
		["Coord"]="Coordinate",
		["Tab1"]="Minimap",
		["Tab2"]="Buttons",
		["Left"]="Left-Click toggles the Minimap.",
		["Right"]="Right-Click to open Minimap buttons menu.",
		["Middle"]="Middle-Click to toggle Worldmap.",
		["Saved"]="config saved.",
		["Load"]="loaded, type",
		["ToConfig"]="to config.",
	},
	["SDL"]={
		["In"] = "Damage In",
		["Out"] = "Damage Out",
		["AddOnDescription"] = "Shows incoming and outgoing damage and heals in small movable text areas.",
		["Enable"] = "Enable Add-on",
		["IncomingDamage"] = "Show Incoming Damage",
		["IncomingHeals"] = "Show Incoming Heals",
		["Loaded"] = "loaded",
		["Lock"] = "Lock Frame Positions",
		["OutgoingDamage"] = "Show Outgoing Damage",
		["OutgoingHeals"] = "Show Outgoing Heals",
		["ShowDamageSource"] = "Show Damage Source",
		["ShowHealSource"] = "Show Healing Source",
	},
}