XBar.Lng = {
	["Ttip"]={
		["CfgBtn1"]="XBar 設定",
		["CfgBtn2"]="點擊左鍵開啟設定介面\n右鍵開啟插件選單\n中鍵開關自動前進",
		["SysBtn1"]="系統功能",
		["SysBtn2"]="點擊左鍵開啟主選單\n右鍵開啟系統選單\n中鍵重新載入",
		["DspBtn1"]="點擊左鍵開啟傳送之書介面\n右鍵開關世界地圖\n中鍵設定畫質為低階",
		["SndBtn1"]="點擊左鍵開啟世界搜尋\n右鍵開啟副本進度\n中鍵靜音",

		["Ammo1"]="點擊左鍵開啟任務日誌\n右鍵開啟卡片圖鑑",

		["Bag1"]="點擊左鍵開啟背包\n右鍵預覽銀行或開啟隨身銀行",

		["Class1"]="點擊左鍵開啟角色介面\n右鍵開啟套裝技能\n中鍵開啟稱號介面\nCtrl + 右鍵移除目前稱號",

		["Clock1"]="點擊左鍵切換時制\n右鍵切換時間或日期\n按住 Shift + 左鍵切換這次在線或總在線時數",
		["Clock2"]="在線總時",

		["Craft1"]="採集",
		["Craft2"]="點擊左鍵開啟魔幻寶盒\n右鍵開啟符文解離",
		["Craft3"]="上一次 / 重複次數",
		["Craft4"]="數量",

		["Dps1"]="DPS/耐久度/能力",
		["Dps2"]="點擊左鍵開啟耐久度框架\n右鍵切換裝備",

		["Exp1"]="XP/TP",
		["Exp2"]="點擊左鍵開啟技能介面\n右鍵開啟生產介面",
		["Exp3"]="當前",
		["Exp4"]="需要",
		["Exp5"]="上一次",
		["Exp6"]="需要殺怪數",
		["Exp7"]="目前 TP",

		["Friend1"]="點擊左鍵聯絡好友\n右鍵開啟關係列表",
		["Friend2"]="上線好友",
		["Friend3"]="群組：",

		["Guild1"]="點擊左鍵聯絡在線成員\n右鍵開啟公會介面",
		["Guild2"]="成員",

		["Appointment"]="未報名",
		["Failed"]="無對手",
		["Disable"]="|cffFFAA00未開放|r",
		["Prepare"]="|cffFFAA00準備中|r",
		["Fight"]="|cffFFAA00戰鬥中（未進入）|r",
		["Fighting"]="|cffFFAA00戰鬥中（已進入）|r",
		["FightEnd"]="Finished",

		["Mail1"]="郵件/拍賣場已賣出物品",
		["Mail2"]="點擊左鍵開啟信箱\n右鍵開啟夥伴介面",
		["Mail3"]="已售出",

		["Money1"]="點擊左鍵開啟商城背包\n右鍵開啟商城",
		["Money2"]="獲得",
		["Money3"]="花費",
		["Money4"]="結餘",

		["Ping1"]="性能",
		["Ping2"]="點擊左鍵開啟傳送之書介面",
		["Ping3"]="右鍵開啟世界搜尋",

		["EQDmg1"]="更改文字顯示方式",
		["EQDmg2"]="- 此介面可以修理或更換裝備\n- 按|cffFFAA00左鍵|r使用顯示在最右邊您擁有的修理槌",
		["AvgDur"]="平均耐久度",
		["LowDur"]="最低耐久度",

		["CR_REST"]="按住 Ctrl + 右鍵重置",
		["LMOUSE_WSP"]="點擊左鍵密語",
		["RMOUSE_INV"]="右鍵邀請組隊",
		["SCROLL_ON"]="滑鼠滾輪捲動頁面",
		["Loc"]="位置：",
		["Note"]="筆記",
		["Sys_SC1"]="返回選角畫面",

		["Bon_Bu1"]="指令查詢",
		["Bon_Bu2"]="開啟瀏覽器",
		["Bon_Bu3"]="只在隊伍時顯示仇恨",
		["Bon_Bu4"]="目標預覽",
		["Bon_Bu5"]="招喚/喚回寵物三",
		["Bon_Bu6"]="招喚/喚回寵物二",
		["Bon_Bu7"]="招喚/喚回寵物一",
		["Bon_Bu8"]="切換武器",
		["Bon_Bu9"]="儲存隊伍",
		["Bon_Bu10"]="儲存並離開隊伍",
		["Bon_Bu11"]="邀請組隊",
		["Bon_Bu12"]="儲存並重新組隊",
	},
	["Config"]={
		["saved"]="|cffFFE855XBar|r 選項設定成功~",
		["help"]="XBar Help:",
		["toggle_xbar"]="|cffFFE855/xb on|r - 開關 XBar 背景",
		["toggle_main"]="|cffFFE855/xb main|r - 開關主選單框架",
		["toggle_expf"]="|cffFFE855/xb exp|r - 開關經驗值條",
		["loaded1"]="|cffFFE855XBar [TW] ",
		["loaded2"]="|r 已讀取，輸入 |cffFFE855/xbar|r 開啟設定介面",
		["Title"]="XBar 插件管理系統",
		["Descr"]="nigrangelus:\n I wrote this once to just enhance the XBar's configurability.\nIts able to let any addon be a part of itself, so there is no need to have various windows opened.",
		["Info"]="Shift + 滑鼠右鍵移動 XBar 的按鈕\n滑鼠滾輪捲動聊天視窗\n您可刪除您不需要的按鈕檔案\n刪除按鈕後請重新啟動遊戲",
		["EnableXBar"]="啟用 XBar",
		["Top"]="置於上方",
		["Bottom"]="置於下方",
		["Main4"]="顯示全部主按鈕",
		["Main2"]="顯示兩個主按鈕",
		["Main0"]="隱藏全部主按鈕",
		["Style"]="選擇樣式",
		["HideOriginalXP"]="隱藏原始經驗值條",
		["HideOriginalED"]="隱藏原始裝備耐久度介面",
		["Text1"]="顯示敘述 1",
		["Text2"]="顯示敘述 2",
		["Value"]="內容（最多 255 字元）",
		["ValueL1"]="內容 A（最多 255 字元）|cffFFE855[左鍵]|r",
		["ValueL2"]="內容 B（最多 255 字元）|cffFFE855[左鍵]|r",
		["ValueR"]="內容 C（最多 255 字元）|cffFFE855[右鍵]|r",
		["ValueSL1"]="內容 A（最多 255 字元）|cffFFE855[Shift + 左鍵]|r",
		["ValueSL2"]="內容 B（最多 255 字元）|cffFFE855[Shift + 左鍵]|r",
		["Head"]="|cffFFE855代碼顯示|r\n\n",

		["Count"]="%s數量",
		["Name"]="%s名稱",

		["Bag1"]="%s已使用空間",
		["Bag2"]="背包總空間",
		["Bag3"]="%s使用的百分比",

		["Class1"]="第三職",
		["Class2"]="%s等級",
		["Class3"]="已完成任務",

		["Clock1"]="在線時間",
		["Clock2"]="總共在線時間",

		["Craft1"]="%s等級",
		["Craft2"]="%s經驗值",
		["Craft3"]="升級還需要%s的次數",
		["Craft4"]="上次%s的經驗值",

		["Dps1"]="平均每秒%s",
		["Dps2"]="上一次的%s",
		["Dps3"]="殺敵數量統計",

		["Exp1"]="升級還需要的 XP",
		["Exp2"]="升級共需要的 XP",
		["Exp3"]="目前 XP 以 % 顯示",
		["Exp4"]="需要 XP 以 % 顯示",
		["Exp5"]="升級前需要殺怪的數量",
		["Exp6"]="上一次所得到的 %s",
		["Exp7"]="這次上線獲得的 %s",
		["Exp8"]="所有 TP",
		["Exp9"]="已用 TP",
		["Exp10"]="房屋 %s 獎勵",
		["Exp11"]="%s 負債",
		["Exp12"]="%s XP",
		["Exp13"]="%s XP 最大值",

		["Friend1"]="好友在線人數",
		["Friend2"]="好友總數",

		["Guild1"]="公會成員在線人數",
		["Guild2"]="成員總數",
		["Guild3"]="公會成員等級最大值",

		["Mail1"]="收到的郵件數量",
	},
	["X3"]={
		["AngelSwitch"]="XBar: 已切換套裝上的武器！",
		["InParty"]="vcThreatMeter 只在隊伍顯示",
		["InCombat"]="vcThreatMeter 戰鬥中顯示",
		["Msg1"]="XBar 指令說明（你可將指令加入巨集中）",
		["Msg2"]="|cffFFE855/run XBar.heal()|r－自動選擇團隊中最低血量者並治療。",
		["Msg3"]="|cffFFE855/run XBar.rogue()|r－自動依減益狀態、冷卻、能量使用影行者技能。",
		["Msg4"]="|cffFFE855/run XBar.party()|r－依序選擇隊友一到五。",
		["Msg5"]="|cffFFE855/run XBar.switch()|r－切換套裝上的武器，請按三次。",
		["Msg6"]="|cffFFE855/run XBar.strip()|r－脫穿目前所有裝備",
		["Msg7"]="|cffFFE855/run XBar.pet1()|r－招喚/喚回寵物一",
		["Msg8"]="|cffFFE855/run XBar.pet2()|r－招喚/喚回寵物二",
		["Msg9"]="|cffFFE855/run XBar.pet3()|r－招喚/喚回寵物三",
		["Msg10"]="|cffFFE855/run XBar.preview()|r－目標預覽",
	},
	["XM"]={
		["Anchor"]="顯示拖曳錨點",
		["Size"]="獨立尺寸",
		["Style"]="選擇樣式",
		["Switch"]="快速切換",
		["Zone"]="區域名稱",
		["Time"]="線上時間圖示",
		["Coord"]="座標",
		["Tab1"]="小地圖",
		["Tab2"]="按鈕",
		["Left"]="點擊左鍵開關小地圖",
		["Right"]="右鍵開關小地圖按鈕選單",
		["Middle"]="中鍵開關世界地圖",
		["Saved"]="已儲存設定",
		["Load"]="已讀取，輸入",
		["ToConfig"]="開啟設定介面",
	},
	["SDL"]={
		["In"] = "輸入",
		["Out"] = "輸出",
		["AddOnDescription"] = "在兩個個可移動的區塊顯示傷害和治療的輸入與輸出",
		["Enable"] = "啟用插件",
		["IncomingDamage"] = "顯示傷害輸入",
		["IncomingHeals"] = "顯示治療輸入",
		["Loaded"] = "已讀取",
		["Lock"] = "固定區塊位置",
		["OutgoingDamage"] = "顯示傷害輸出",
		["OutgoingHeals"] = "顯示治療輸出",
		["ShowDamageSource"] = "顯示傷害來源",
		["ShowHealSource"] = "顯示治療來源",
	},
}