-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/charplan/localization/
--]]

Charplan.L =
{
	["BY_CLASS"] = "Base",
	["BY_SET"] = "Sets",
	["BY_SKILL"] = "Skill",
	["CONTEXT_CLEAR"] = "Leeren",
	["CONTEXT_MENU"] = "Zum Plan hinzufügen",
	["CONTEXT_PIMPME"] = "Pimp",
	["CONTEXT_SEARCH"] = "Suche",
	["CONTEXT_SHARE"] = "Kopiere zu allen Gegenst.",
	["CONTEXT_SHARE_RUNES"] = "Runen kopieren",
	["CONTEXT_SHARE_STATS"] = "Stats kopieren",
	["CONTEXT_SHARE_VALUES"] = "Basiswerte kopieren",
	["DLG_SAVENAME"] = "Namen eingeben",
	["DLG_WAIT_INV"] = "Bitte warten während ihre Ausrüstung übertragen wird",
	["ENUMERATE_CANCELED"] = "Übertragung abgebrochen",
	["ERROR_NO_VALID_ITEM"] = "Kein ausrüstbarer Gegenstand.",
	["ERROR_NOSLOT"] = "Ein freier Rucksack platz wird für das Importieren benötigt.",
	["ERROR_PICKEDUPITEM"] = "Beim Übertragen ist ein Fehler aufgetreten! Bitte prüfen Sie ihre Ausrüstung!",
	["ERROR_SEARCH_SKIN"] = "«%s»! Skin konnte nicht eindeutig erkannt werden und könnte falsch sein!",
	["MENU_CLEARALL"] = "Ausrüstung leeren",
	["MENU_COMPARE"] = "Vergleichswerte",
	["MENU_DEL"] = "Speicherstand löschen",
	["MENU_IMPORT"] = "Ausrüstung importieren",
	["MENU_LOAD"] = "Ausrüstung laden",
	["MENU_SAVE"] = "Ausrüstung speichern",
	["MENU_SAVEAS"] = "Ausrüstung speichern unter...",
	["MENU_TITLE"] = "Menu",
	["PIMP_CLEAR"] = "Löschen",
	["PIMP_CLEAR_TIP"] = "benötigt Doppelklick",
	["PIMP_COPY"] = "Kopieren nach…",
	["PIMP_COPY_TO_ALL"] = "… allen Gegenständen",
	["PIMP_FILTER1"] = "<Name>",
	["PIMP_FILTER2"] = "<Stat1>",
	["PIMP_FILTER3"] = "<Stat2>",
	["PIMP_FILTER4"] = "min",
	["PIMP_FILTER5"] = "Min/Max der Stats Werte",
	["PIMP_PLUS"] = "Plus",
	["PIMP_RUNE"] = "Rune %i",
	["PIMP_STAT"] = "Stat %i",
	["SEARCH_BASE_STATS"] = "Dmg/Def",
	["SEARCH_CONTEXT_SKIN"] = "Skin übernehmen",
	["SEARCH_CONTEXT_SUIT"] = "Ganzes Set anlegen",
	["SEARCH_CONTEXT_TAKE"] = "Gegenstand anlegen",
	["SEARCH_CONTEXT_WEB"] = "Im Webbrowser öffnen",
	["SEARCH_DROPPED"] = "Dropped in %s by %s",
	["SEARCH_FILTER"] = "Filter",
	["SEARCH_FILTER_NIL"] = "Alle",
	["SEARCH_FILTER_STATS"] = "Stats",
	["SEARCH_GENDER"] = "alle Geschlechter",
	["SEARCH_MADE"] = "Erstellt durch %s",
	["SEARCH_NOSTATLESS"] = "Kostüme ausblenden",
	["SEARCH_NOSTATLESS_TIP"] = "Blended Gegenst. ohne Zusatzwerte aus (bsp: Flügel, Kostüme)",
	["SEARCH_ONLYSET"] = "Nur Item-Sets",
	["SEARCH_POWER_MODIFY"] = "%i Dura",
	["SEARCH_RARITY_EXACT"] = "nur diese Qualität",
	["SEARCH_RARITY_MINIMUM"] = "mindestens diese Qualität",
	["SEARCH_SELLED"] = "Wird verkauf im Shop id %d für",
	["SEARCH_STATS"] = "Stats",
	["SEARCH_TITLE"] = "Gegenstandssuche",
	["SEARCH_TYPE"] = "Type",
	["SEARCH_UNIQUE_SKINS"] = "Eindeutige Skins",
	["SEARCH_UNNAMED"] = "Unbenannte Gegenstände",
	["SEARCH_USE_SLOT1"] = "In Slot1",
	["SEARCH_USE_SLOT2"] = "In Slot2",
	["SEARCH_WEBSITE"] = "http://de.runesdatabase.com/item/%i",
	["TITLE_EMPTY"] = "<unbenannt>"
}


Charplan.L.STAT_SHORTS =
{
}

Charplan.L.STAT_NAMES =
{
}

