-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/charplan/localization/
--]]

Charplan.L =
{
	["BY_CLASS"] = "Base",
	["BY_SET"] = "Sets",
	["BY_SKILL"] = "Habilidad",
	["CONTEXT_CLEAR"] = "Limpiar",
	["CONTEXT_MENU"] = "Añadir al plan",
	["CONTEXT_PIMPME"] = "Customizar",
	["CONTEXT_SEARCH"] = "Buscar",
	["CONTEXT_SHARE"] = "Compartir a todo el equipo",
	["CONTEXT_SHARE_RUNES"] = "Copiar runas",
	["CONTEXT_SHARE_STATS"] = "Copiar stats",
	["CONTEXT_SHARE_VALUES"] = "Copiar valores base",
	["DLG_SAVENAME"] = "Entrar nombre",
	["DLG_WAIT_INV"] = "Por favor espera mientras se enumeratu equipo...",
	["ENUMERATE_CANCELED"] = "Enumeración cancelada!",
	["ERROR_NO_VALID_ITEM"] = "Equipo no valido",
	["ERROR_NOSLOT"] = "Hace falta un espacio libre en tu mochila para importar tu equipo actual!",
	["ERROR_PICKEDUPITEM"] = "Ha habido un problema mientras se escaneba tu equipo! Revisa tu equipo actual!",
	["ERROR_SEARCH_SKIN"] = "El Skin es ambiguo y podría ser erroneo para «%s»!",
	["MENU_CLEARALL"] = "Limpiar objetos",
	["MENU_COMPARE"] = "Comparar estadísticas",
	["MENU_DEL"] = "Borrar guardado",
	["MENU_IMPORT"] = "Importar equipo actual...",
	["MENU_LOAD"] = "Cargar Items",
	["MENU_SAVE"] = "Guardar objetos",
	["MENU_SAVEAS"] = "Guardar objetos como...",
	["MENU_TITLE"] = "Menú",
	["PIMP_CLEAR"] = "Limpiar",
	["PIMP_CLEAR_TIP"] = "Requiere doble clic",
	["PIMP_COPY"] = "Compartir",
	["PIMP_COPY_TO_ALL"] = [=[... todos los items
]=],
	["PIMP_FILTER1"] = "<Nombre>",
	["PIMP_FILTER2"] = "<Stat1>",
	["PIMP_FILTER3"] = "<Stat2>",
	["PIMP_FILTER4"] = "min",
	["PIMP_FILTER5"] = "max",
	["PIMP_PLUS"] = "Más",
	["PIMP_RUNE"] = "Runa %i",
	["PIMP_STAT"] = "Stat %i",
	["SEARCH_BASE_STATS"] = "Daño/Def",
	["SEARCH_CONTEXT_SKIN"] = "Aplicar Skin",
	["SEARCH_CONTEXT_SUIT"] = "Equipar Suit",
	["SEARCH_CONTEXT_TAKE"] = "Equipar objeto",
	["SEARCH_CONTEXT_WEB"] = "Abrir en Web",
	["SEARCH_DROPPED"] = "Obtenido en: %s de %s",
	["SEARCH_FILTER"] = "Filtro",
	["SEARCH_FILTER_NIL"] = "Todo",
	["SEARCH_FILTER_STATS"] = "Stats",
	["SEARCH_GENDER"] = "Todos los géneros",
	["SEARCH_MADE"] = "Hecho por",
	["SEARCH_NOSTATLESS"] = "Esconder  customización",
	["SEARCH_NOSTATLESS_TIP"] = "No mostrar objetos sin los atributos.",
	["SEARCH_ONLYSET"] = "Sólo objetos de set",
	["SEARCH_POWER_MODIFY"] = "%i Dura",
	["SEARCH_RARITY_EXACT"] = "Sólo esta rareza",
	["SEARCH_RARITY_MINIMUM"] = "Desde esta rareza",
	["SEARCH_SELLED"] = "Vendido en tienda id %d por",
	["SEARCH_STATS"] = "Stats",
	["SEARCH_TITLE"] = "Buscar objeto",
	["SEARCH_TYPE"] = "Tipo",
	["SEARCH_UNIQUE_SKINS"] = "Apariencia única",
	["SEARCH_UNNAMED"] = "Items sin nombre",
	["SEARCH_USE_SLOT1"] = "Poner en Slot 1",
	["SEARCH_USE_SLOT2"] = "Poner en Slot 2",
	["SEARCH_WEBSITE"] = "http://www.runesdatabase.com/item/%i",
	["TITLE_EMPTY"] = "<sinnombre>"
}

Charplan.L.STAT_SHORTS =
{
}

Charplan.L.STAT_NAMES =
{
}
