-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/charplan/localization/
--]]

Charplan.L =
{
	["BY_CLASS"] = "Base",
	["BY_SET"] = "Set",
	["BY_SKILL"] = "Abilità",
	["CONTEXT_CLEAR"] = "Pulisci",
	["CONTEXT_MENU"] = "Aggiungi al piano",
	["CONTEXT_PIMPME"] = "Migliora",
	["CONTEXT_SEARCH"] = "Cerca",
	["CONTEXT_SHARE"] = "Condividi tutti gli equipaggiamenti",
	["CONTEXT_SHARE_RUNES"] = "copia rune",
	["CONTEXT_SHARE_STATS"] = "copia statistiche",
	["CONTEXT_SHARE_VALUES"] = "copia valori di base",
	["DLG_SAVENAME"] = "Inserisci Nome",
	["DLG_WAIT_INV"] = "Attendi mentre numeriamo il tuo equipaggiamento...",
	["ENUMERATE_CANCELED"] = "Numerazione annullata!",
	["ERROR_NO_VALID_ITEM"] = "Equipaggiamento non valido.",
	["ERROR_NOSLOT"] = "E' necessario uno spazio libero nella Sacca per imporatare l'equipaggiamento corrente!",
	["ERROR_PICKEDUPITEM"] = "C'è stato un problema mentre acquisivamo il tuo equipaggiamento! Controlla il tuo equipaggiamento attuale!",
	["ERROR_SEARCH_SKIN"] = "La grafica è ambigua e potrebbe essere sbagliata per «%s»!",
	["MENU_CLEARALL"] = "Pulisci gli Oggetti",
	["MENU_COMPARE"] = "Compara statistiche",
	["MENU_DEL"] = "Cancellamento salvato",
	["MENU_IMPORT"] = "Importa l'equipaggiamento corrente...",
	["MENU_LOAD"] = "Carica Oggetti",
	["MENU_SAVE"] = "Salva Oggetti",
	["MENU_SAVEAS"] = "Salva Oggetti come...",
	["MENU_TITLE"] = "Menù",
	["PIMP_CLEAR"] = "Pulisci",
	["PIMP_CLEAR_TIP"] = "richiede doppio click",
	["PIMP_COPY"] = "Copia a...",
	["PIMP_COPY_TO_ALL"] = "... tutti gli oggetti",
	["PIMP_FILTER1"] = "<Nome>",
	["PIMP_FILTER2"] = "<Statistica1>",
	["PIMP_FILTER3"] = "<Statistica2>",
	["PIMP_FILTER4"] = "min",
	["PIMP_FILTER5"] = "max",
	["PIMP_PLUS"] = "Più",
	["PIMP_RUNE"] = "Runa %i",
	["PIMP_STAT"] = "Statistica %i",
	["SEARCH_BASE_STATS"] = "Danno/Difesa",
	["SEARCH_CONTEXT_SKIN"] = "Applica Grafica",
	["SEARCH_CONTEXT_SUIT"] = "Equipaggia l'Abito",
	["SEARCH_CONTEXT_TAKE"] = "Equipaggia Oggetto",
	["SEARCH_CONTEXT_WEB"] = "Apri nel Browser",
	["SEARCH_DROPPED"] = "Ottenuto in: %s da %s",
	["SEARCH_FILTER"] = "Filtra",
	["SEARCH_FILTER_NIL"] = "Tutti",
	["SEARCH_FILTER_STATS"] = "Statistiche",
	["SEARCH_GENDER"] = "tutti i generi",
	["SEARCH_MADE"] = "Fatto da %s",
	["SEARCH_NOSTATLESS"] = "nascondi costumi",
	["SEARCH_NOSTATLESS_TIP"] = "Non mostrare oggetti senza attributi (es. costumi, ali)",
	["SEARCH_ONLYSET"] = "Mostra oggetti solo da I",
	["SEARCH_POWER_MODIFY"] = "%i Durabilità",
	["SEARCH_RARITY_EXACT"] = "solo questa rarità",
	["SEARCH_RARITY_MINIMUM"] = "al meno questa rarità",
	["SEARCH_SELLED"] = "Venduto al negozio id %d per",
	["SEARCH_STATS"] = "Statistiche",
	["SEARCH_TITLE"] = "Cerca oggetto",
	["SEARCH_TYPE"] = "Tipo",
	["SEARCH_UNIQUE_SKINS"] = "Grafiche uniche",
	["SEARCH_UNNAMED"] = "oggetti senza nome",
	["SEARCH_USE_SLOT1"] = "Metti nello Spazio 1",
	["SEARCH_USE_SLOT2"] = "Metti nello Spazio 2",
	["SEARCH_WEBSITE"] = "http://www.runesdatabase.com/item/%i",
	["TITLE_EMPTY"] = "<senzanome>"
}

Charplan.L.STAT_SHORTS =
{
}

Charplan.L.STAT_NAMES =
{
}
