-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/charplan/localization/
--]]

Charplan.L =
{
	["BY_CLASS"] = "ベース",
	["BY_SET"] = "セット",
	["BY_SKILL"] = "スキル",
	["CONTEXT_CLEAR"] = "クリア",
	["CONTEXT_MENU"] = "[CharPlan]計画を追加",
	["CONTEXT_PIMPME"] = "詳細",
	["CONTEXT_SEARCH"] = "検索",
	["CONTEXT_SHARE"] = "全装備の共有",
	["CONTEXT_SHARE_RUNES"] = "ルーンステータスをコピー",
	["CONTEXT_SHARE_STATS"] = "ステータスをコピー",
	["CONTEXT_SHARE_VALUES"] = "基本値をコピー",
	["DLG_SAVENAME"] = "名前入力",
	["DLG_WAIT_INV"] = "装備を列挙しています。お待ちください。",
	["ENUMERATE_CANCELED"] = "列挙処理はキャンセルされました。",
	["ERROR_NO_VALID_ITEM"] = "有効な装備でありません。",
	["ERROR_NOSLOT"] = "装備をインポートするために、バッグの空スロットが必要です。",
	["ERROR_PICKEDUPITEM"] = "装備の走査中に、問題が発生しました。現在の装備を確認してください。",
	["ERROR_SEARCH_SKIN"] = "スキンは曖昧で、«%s»には誤っているかもしれませんでした。",
	["MENU_CLEARALL"] = "アイテムをクリア",
	["MENU_COMPARE"] = "ステータス比較",
	["MENU_DEL"] = "削除",
	["MENU_IMPORT"] = "現在の装備のインポート中...",
	["MENU_LOAD"] = "アイテムのロード",
	["MENU_SAVE"] = "アイテムの保存",
	["MENU_SAVEAS"] = "名前をつけて保存",
	["MENU_TITLE"] = "メニュー",
	["PIMP_CLEAR"] = "クリア",
	["PIMP_CLEAR_TIP"] = "要ダブルクリック",
	["PIMP_COPY"] = [=[コピー
]=],
	["PIMP_COPY_TO_ALL"] = [=[… 全アイテム
]=],
	["PIMP_FILTER1"] = "<Name>",
	["PIMP_FILTER2"] = "<Stat1>",
	["PIMP_FILTER3"] = "<Stat2>",
	["PIMP_FILTER4"] = "min",
	["PIMP_FILTER5"] = "max",
	["PIMP_PLUS"] = "プラス",
	["PIMP_RUNE"] = "ルーン %i",
	["PIMP_STAT"] = "ステータス %i",
	["SEARCH_BASE_STATS"] = "Dmg/Def",
	["SEARCH_CONTEXT_SKIN"] = "スキン適用",
	["SEARCH_CONTEXT_SUIT"] = "スーツスキル",
	["SEARCH_CONTEXT_TAKE"] = "装備アイテム",
	["SEARCH_CONTEXT_WEB"] = "ブラウザで開く",
	["SEARCH_DROPPED"] = "%s の %s より入手",
	["SEARCH_FILTER_NIL"] = "全装備のタイプ",
	["SEARCH_FILTER_STATS"] = "ステータス",
	["SEARCH_GENDER"] = "性別制限なし",
	["SEARCH_MADE"] = "%s により製作されました。",
	["SEARCH_NOSTATLESS"] = "見た目を隠す",
	["SEARCH_NOSTATLESS_TIP"] = "属性値のない装備を隠す（翼など）",
	["SEARCH_ONLYSET"] = "セット装備のみ",
	["SEARCH_POWER_MODIFY"] = "耐久 %i",
	["SEARCH_RARITY_EXACT"] = "このレアのみ",
	["SEARCH_RARITY_MINIMUM"] = "少なくともこのレア",
	["SEARCH_SELLED"] = "id %d は売れました。",
	["SEARCH_STATS"] = "状態",
	["SEARCH_TITLE"] = "アイテム検索",
	["SEARCH_TYPE"] = "タイプ",
	["SEARCH_UNIQUE_SKINS"] = "ユニークスキン",
	["SEARCH_USE_SLOT1"] = "スロット１に置く",
	["SEARCH_USE_SLOT2"] = "スロット２に置く",
	["SEARCH_WEBSITE"] = "http://www.runesdatabase.com/item/%i",
	["TITLE_EMPTY"] = "<名前なし>"
}

Charplan.L.STAT_SHORTS =
{
}

Charplan.L.STAT_NAMES =
{
}
