-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/charplan/localization/
--]]

Charplan.L =
{
}

Charplan.L.STAT_SHORTS =
{
}

Charplan.L.STAT_NAMES =
{
}
