-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/charplan/localization/
--]]

Charplan.L =
{
	["BY_CLASS"] = "Bazowe",
	["BY_SET"] = "Setowe",
	["BY_SKILL"] = "Umiejętności",
	["CONTEXT_CLEAR"] = "Usuń",
	["CONTEXT_MENU"] = "Dodaj do projektu",
	["CONTEXT_PIMPME"] = "Edytuj",
	["CONTEXT_SEARCH"] = "Szukaj",
	["CONTEXT_SHARE"] = "Zastosuj w całym ekwipunku",
	["CONTEXT_SHARE_RUNES"] = "skopiuj runy",
	["CONTEXT_SHARE_STATS"] = "skopiuj statystyki",
	["CONTEXT_SHARE_VALUES"] = "skopiuj wartości bazowe",
	["DLG_SAVENAME"] = "Wpisz nazwę",
	["DLG_WAIT_INV"] = "Proszę czekać, trwa sprawdzanie twojego ekwipunku...",
	["ENUMERATE_CANCELED"] = "Sprawdzanie anulowane!",
	["ERROR_NO_VALID_ITEM"] = "Nieprawidłowy ekwipunek.",
	["ERROR_NOSLOT"] = "Aby importować twój aktualny ekwipunek, jest potrzebne wolne miejsce w plecaku!",
	["ERROR_PICKEDUPITEM"] = "Wystąpił problem podczas skanowania ekwipunku! Sprawdź swój aktualny ekwipunek!",
	["ERROR_SEARCH_SKIN"] = "Wygląd został zmieniony i może być niewłaściwy dla «%s»!",
	["MENU_CLEARALL"] = "Usuń przedmioty",
	["MENU_COMPARE"] = "Porównaj statystyki",
	["MENU_DEL"] = "Usuń zapis",
	["MENU_IMPORT"] = "Importuj aktualny ekwipunek...",
	["MENU_LOAD"] = "Wgraj przedmioty",
	["MENU_SAVE"] = "Zapisz przedmioty",
	["MENU_SAVEAS"] = "Zapisz przedmioty jako...",
	["MENU_TITLE"] = "Menu",
	["PIMP_CLEAR"] = "Wyczyść",
	["PIMP_CLEAR_TIP"] = "wymaga podwójnego kliknięcia",
	["PIMP_COPY"] = "Skopiuj do...",
	["PIMP_COPY_TO_ALL"] = "... wszystkie przedmioty",
	["PIMP_FILTER1"] = "<Nazwa>",
	["PIMP_FILTER2"] = "<Statystyka1>",
	["PIMP_FILTER3"] = "<Statystyka2>",
	["PIMP_FILTER4"] = "min.",
	["PIMP_FILTER5"] = "maks.",
	["PIMP_PLUS"] = "Plus",
	["PIMP_RUNE"] = "Runa %i",
	["PIMP_STAT"] = "Stat. %i",
	["SEARCH_BASE_STATS"] = "Dmg/Def",
	["SEARCH_CONTEXT_SKIN"] = "Zastosuj wygląd",
	["SEARCH_CONTEXT_SUIT"] = "Wyposaż w zestaw",
	["SEARCH_CONTEXT_TAKE"] = "Załóż przedmiot",
	["SEARCH_CONTEXT_WEB"] = "Otwórz w przeglądarce www",
	["SEARCH_DROPPED"] = "Wypada w: %s z %s",
	["SEARCH_FILTER"] = "Filtr",
	["SEARCH_FILTER_NIL"] = "Wszystko",
	["SEARCH_FILTER_STATS"] = "Statystyki",
	["SEARCH_GENDER"] = "każda płeć",
	["SEARCH_MADE"] = "Wykonane z %s",
	["SEARCH_NOSTATLESS"] = "Ukryj kostiumy",
	["SEARCH_NOSTATLESS_TIP"] = "Nie pokazuj przedmiotów bez atrybutów (np. kostiumy, skrzydła)",
	["SEARCH_ONLYSET"] = "tylko przedmioty z zestawu",
	["SEARCH_POWER_MODIFY"] = "Trwałość %i",
	["SEARCH_RARITY_EXACT"] = "tylko ta rzadkość",
	["SEARCH_RARITY_MINIMUM"] = "co najmniej ta rzadkość",
	["SEARCH_SELLED"] = "Sprzedane w sklepie o ID %d za",
	["SEARCH_STATS"] = "Statystyki",
	["SEARCH_TITLE"] = "Szukaj przedmiotu",
	["SEARCH_TYPE"] = "Rodzaj",
	["SEARCH_UNIQUE_SKINS"] = "Unikalne wyglądy",
	["SEARCH_UNNAMED"] = "nienazwane przedmioty",
	["SEARCH_USE_SLOT1"] = "Umieść w gnieździe 1",
	["SEARCH_USE_SLOT2"] = "Umieść w gnieździe 2",
	["SEARCH_WEBSITE"] = "http://pl.runesdatabase.com/item/%i",
	["TITLE_EMPTY"] = "<bez-nazwy>"
}

Charplan.L.STAT_SHORTS =
{
}

Charplan.L.STAT_NAMES =
{
}
