-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/charplan/localization/
--]]

Charplan.L =
{
	["BY_CLASS"] = "Базовое",
	["BY_SET"] = "От комплектов",
	["BY_SKILL"] = "От пассивок",
	["CONTEXT_CLEAR"] = "Очистить",
	["CONTEXT_MENU"] = "Добавить к снаряжению",
	["CONTEXT_PIMPME"] = "Улучшить ",
	["CONTEXT_SEARCH"] = "Выбрать из базы",
	["CONTEXT_SHARE"] = "Копировать улучшения",
	["CONTEXT_SHARE_RUNES"] = "копировать руны",
	["CONTEXT_SHARE_STATS"] = "копировать статы",
	["CONTEXT_SHARE_VALUES"] = "копировать базовые значения",
	["DLG_SAVENAME"] = "Название комплекта",
	["DLG_WAIT_INV"] = "Дождитесь окончания импорта снаряжения",
	["ENUMERATE_CANCELED"] = "Импорт прерван!",
	["ERROR_NO_VALID_ITEM"] = "Этот предмет нельзя экипировать.",
	["ERROR_NOSLOT"] = "Для импорта вашего снаряжения в аддон необходим хотя бы один свободный слот в рюкзаке!",
	["ERROR_PICKEDUPITEM"] = "Возникла проблема при импорте снаряжения, проверьте, не заблокирован ли какой-то предмет в нём?",
	["ERROR_SEARCH_SKIN"] = "Эта внешка у многих предметов: «%s»!",
	["MENU_CLEARALL"] = "Сбросить снаряжение",
	["MENU_COMPARE"] = "Сравнить с",
	["MENU_DEL"] = "Удалить сохраненный",
	["MENU_IMPORT"] = "Импортировать снаряжение персонажа",
	["MENU_LOAD"] = "Загрузить снаряжение",
	["MENU_SAVE"] = "Сохранить",
	["MENU_SAVEAS"] = "Сохранить как…",
	["MENU_TITLE"] = "Действия",
	["PIMP_CLEAR"] = "Очистить",
	["PIMP_CLEAR_TIP"] = "Двойной клик для удаления!",
	["PIMP_COPY"] = "Скопировать →",
	["PIMP_COPY_TO_ALL"] = "… на все вещи",
	["PIMP_FILTER1"] = "<Имя>",
	["PIMP_FILTER2"] = "<стат 1>",
	["PIMP_FILTER3"] = "<стат 2>",
	["PIMP_FILTER4"] = "min",
	["PIMP_FILTER5"] = "max",
	["PIMP_PLUS"] = "Заточка",
	["PIMP_RUNE"] = "Руна %i",
	["PIMP_STAT"] = "Стат %i",
	["SEARCH_BASE_STATS"] = "Урон/ФЗ",
	["SEARCH_CONTEXT_SKIN"] = "В качестве внешки",
	["SEARCH_CONTEXT_SUIT"] = "Экипировать весь комплект",
	["SEARCH_CONTEXT_TAKE"] = "Экипировать",
	["SEARCH_CONTEXT_WEB"] = "Открыть на сайте базы",
	["SEARCH_DROPPED"] = "Падает в «%s» из «%s»",
	["SEARCH_FILTER_NIL"] = "Все",
	["SEARCH_FILTER_STATS"] = "Статы",
	["SEARCH_GENDER"] = "всех полов",
	["SEARCH_MADE"] = "Создаётся из %s",
	["SEARCH_NOSTATLESS"] = "скрыть костюмы",
	["SEARCH_NOSTATLESS_TIP"] = "Исключать внешки без свойств (костюмы, крылья)",
	["SEARCH_ONLYSET"] = "комплекты вещей",
	["SEARCH_POWER_MODIFY"] = "Прочка",
	["SEARCH_RARITY_EXACT"] = "смотреть только этот цвет",
	["SEARCH_RARITY_MINIMUM"] = "смотреть выбранный и выше",
	["SEARCH_SELLED"] = "Продаётся у торговца %d за",
	["SEARCH_STATS"] = "Статы",
	["SEARCH_TITLE"] = "Выбрать снаряжение",
	["SEARCH_TYPE"] = "Тип",
	["SEARCH_UNIQUE_SKINS"] = "уникальные внешки",
	["SEARCH_USE_SLOT1"] = "В слот № 1",
	["SEARCH_USE_SLOT2"] = "В слот № 2",
	["SEARCH_WEBSITE"] = "http://ru.runesdatabase.com/item/%i",
	["TITLE_EMPTY"] = "<без имени>"
}

Charplan.L.STAT_SHORTS =
{
}

Charplan.L.STAT_NAMES =
{
}
