-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/charplan/localization/
--]]

Charplan.L =
{
	["BY_CLASS"] = "基礎",
	["BY_SET"] = "套裝",
	["BY_SKILL"] = "技能",
	["CONTEXT_CLEAR"] = "清除",
	["CONTEXT_MENU"] = "新增到計畫中",
	["CONTEXT_PIMPME"] = "模擬",
	["CONTEXT_SEARCH"] = "搜尋",
	["CONTEXT_SHARE"] = "共用到全部裝備",
	["DLG_SAVENAME"] = "輸入名稱",
	["DLG_WAIT_INV"] = "請稍等，我們正在為您列出裝備…",
	["ENUMERATE_CANCELED"] = "已取消裝備導入！",
	["ERROR_NO_VALID_ITEM"] = "無效的裝備",
	["ERROR_NOSLOT"] = "必須要有一格空的背包才能導入目前的裝備！",
	["ERROR_PICKEDUPITEM"] = "掃描裝備時發生錯誤！請檢查您目前的裝備。",
	["ERROR_SEARCH_SKIN"] = "造型資料模糊，可能是「%s」的問題！",
	["MENU_CLEARALL"] = "清除資料",
	["MENU_COMPARE"] = "資料比對",
	["MENU_DEL"] = "刪除存檔",
	["MENU_IMPORT"] = "導入目前裝備…",
	["MENU_LOAD"] = "讀取資料",
	["MENU_SAVE"] = "儲存資料",
	["MENU_SAVEAS"] = "另存新檔…",
	["MENU_TITLE"] = "計畫選單",
	["PIMP_CLEAR"] = "清除",
	["PIMP_CLEAR_TIP"] = "點擊兩次清除",
	["PIMP_COPY"] = "複製到…",
	["PIMP_COPY_TO_ALL"] = "全部裝備",
	["PIMP_FILTER1"] = "<名稱>",
	["PIMP_FILTER2"] = "<屬性 1>",
	["PIMP_FILTER3"] = "<屬性 2>",
	["PIMP_FILTER4"] = "最小",
	["PIMP_FILTER5"] = "最大",
	["PIMP_PLUS"] = "強化",
	["PIMP_RUNE"] = "符文 %i",
	["PIMP_STAT"] = "魔石 %i",
	["SEARCH_BASE_STATS"] = "傷害 / 防禦",
	["SEARCH_CONTEXT_SKIN"] = "導入造型",
	["SEARCH_CONTEXT_SUIT"] = "裝備套裝",
	["SEARCH_CONTEXT_TAKE"] = "裝備物品",
	["SEARCH_CONTEXT_WEB"] = "在瀏覽器顯示",
	["SEARCH_DROPPED"] = "取得方式：%s－%s",
	["SEARCH_FILTER_NIL"] = "全部",
	["SEARCH_FILTER_STATS"] = "附加能力",
	["SEARCH_GENDER"] = "所有性別",
	["SEARCH_MADE"] = "製作：%s",
	["SEARCH_NOSTATLESS"] = "隱藏商城時裝",
	["SEARCH_NOSTATLESS_TIP"] = "隱藏無屬性的裝備（如：時裝，翅膀）",
	["SEARCH_ONLYSET"] = "只顯示套裝",
	["SEARCH_POWER_MODIFY"] = "%i 耐久度",
	["SEARCH_RARITY_EXACT"] = "只限以上稀有度",
	["SEARCH_RARITY_MINIMUM"] = "至少要以上稀有度",
	["SEARCH_SELLED"] = "在 %d (ID) 商店出售：",
	["SEARCH_STATS"] = "附加能力",
	["SEARCH_TITLE"] = "裝備搜尋",
	["SEARCH_TYPE"] = "類型",
	["SEARCH_UNIQUE_SKINS"] = "特殊造型",
	["SEARCH_USE_SLOT1"] = "放入空格一",
	["SEARCH_USE_SLOT2"] = "放入空格二",
	["SEARCH_WEBSITE"] = "http://tw.runesdatabase.com/item/%i",
	["TITLE_EMPTY"] = "<未命名>"
}

Charplan.L.STAT_SHORTS =
{
}

Charplan.L.STAT_NAMES =
{
}
