-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/eventhelper/localization/
--]]

return
{
["aggro_message1"] = "<arg1> hat Aggro von <arg2>",
["aggro_message2"] = "Du tankst <arg1>",
["buff_message1"] = "<arg1> hat <arg2>",
["colorweave_bothwrong"] = "Beide Falsch!",
["colorweave_lookmatrix"] = "Matrix schauen!",
["colorweave_lookmessage"] = "Message schauen!",
["colorweave_scissor"] = "Gr\195\188n: Schere",
["colorweave_shuttle"] = "Rot: Schiffchen",
["colorweave_thread"] = "Blau: Garn",
["damagereflect_message1"] = "\226\156\157Rest in Pieces\226\156\157 (<arg1>)",
["damagereflect_message2"] = "Damage Stop (<arg1>)",
["donotmove_message"] = "Bleib stehen! (<arg1>)",
["fear_message"] = "<<FEAR>> <arg1>",
["interrupt_message"] = "Unterbrich <arg1>! (<arg2>)",
["pattern_and"] = "<arg1> und <arg2>",
["pattern_or"] = "<arg1> oder <arg2>",
["phasechange_message"] = "Phasenwechsel!",
["phasechange_time_message"] = "Phasenwechsel in <arg1> Sekunden",
["runaway_message"] = "Renn weg! (<arg1>)",
["stayaway_message1"] = "Bleib weg von <arg1>! (<arg2>)",
["stayaway_message2"] = "Bleib weg vom andern Add (<arg2>)",
["ui_active"] = "Eventhelper Aktiv",
["ui_chatmsg"] = "Chatnachrichten schicken",
["ui_chatmsgtochat"] = "Zeige Chatnachrichten im Chat",
["ui_config"] = "Einstellungen",
["ui_debug"] = "Debugger",
["ui_more"] = "Mehr",
["ui_movemessage"] = "Nachrichtenfenster verschieben",
["ui_msgtochat"] = "Zeige Nachrichten im Chat",
["ui_msgtoown"] = "Zeige Nachrichten im Eventhelperframe",
["ui_msgtosys"] = "Zeige Systemnachrichten",
["ui_msgtowarn"] = "Zeige Warnmeldungen",
["ui_scriptconfig"] = "<arg1>-Einstellungen",
["ui_scripts"] = "Skripte",
["ui_sound"] = "Sound",
["ui_version"] = "Version: <arg1>",
["use_message"] = "Benutze <arg1>! (<arg2>)",
}
