-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/eventhelper/localization/
--]]

return
{
["aggro_message1"] = "<arg1> has Aggro of <arg2>",
["aggro_message2"] = "You're tank of <arg1>",
["buff_message1"] = "<arg1> has <arg2>",
["colorweave_bothwrong"] = "Both wrong!",
["colorweave_lookmatrix"] = "Look at matrix!",
["colorweave_lookmessage"] = "Look at message!",
["colorweave_scissor"] = "Green: Scissor",
["colorweave_shuttle"] = "Red: Shuttle",
["colorweave_thread"] = "Blue: Thread",
["damagereflect_message1"] = "\226\156\157Rest in Pieces\226\156\157 (<arg1>)",
["damagereflect_message2"] = "Damage Stop (<arg1>)",
["donotmove_message"] = "Don't Move! (<arg1>)",
["fear_message"] = "<<FEAR>> <arg1>",
["interrupt_message"] = "Interrupt <arg1>! (<arg2>)",
["pattern_and"] = "<arg1> and <arg2>",
["pattern_or"] = "<arg1> or <arg2>",
["phasechange_message"] = "phase change!",
["phasechange_time_message"] = "phase changes in <arg1> seconds",
["runaway_message"] = "Run away! (<arg1>)",
["stayaway_message1"] = "Stay Away from <arg1>! (<arg2>)",
["stayaway_message2"] = "Stay Away from the other Add (<arg1>)",
["ui_active"] = "Eventhelper Active",
["ui_chatmsg"] = "Send Chatmessages",
["ui_chatmsgtochat"] = "Show Chatmessages in Chat",
["ui_config"] = "Settings",
["ui_debug"] = "Debugger",
["ui_more"] = "More",
["ui_movemessage"] = "Move Messageframe",
["ui_msgtochat"] = "Show Messages in Chat",
["ui_msgtoown"] = "Show Messages in own Frame",
["ui_msgtosys"] = "Show Systemmessages",
["ui_msgtowarn"] = "Show Warnmessages",
["ui_scriptconfig"] = "<arg1>-Settings",
["ui_scripts"] = "Scripts",
["ui_sound"] = "Sound",
["ui_version"] = "Version: <arg1>",
["use_message"] = "Use <arg1>! (<arg2>)",
}
