-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/DungeonLoots/localization/
--]]

return
{
["Boss_TT"] = "Boss %d: %s (%d)",
["Boss2_TT"] = "Loots -> %s (%d)",
["BossInstance"] = "Bosse zu Instanzen zuordnen",
["BossList"] = "Bossliste",
["ChangeSortOrder"] = "Sortierung ändern",
["HideWoWMapTeleport"] = "Verberge WoWMap Transportpunkte",
["HideWoWMapZone"] = "Verberge WoWMap Zonenportale",
["instance_memsmsg"] = "In dieser Instanz gibt es %s %s. ",
["instance_memswarning"] = "%s %s zu viel!",
["InstanceList"] = "Instanzliste",
["InstanceOrder"] = "Nach %s sortieren",
["ItemList"] = "Itemliste",
["Itemplus"] = "Item +:",
["MoreButton"] = "Mehr",
["NPCTT"] = [=[HP: %s
Atk: %s, %s
Def: %s, %s
CritRes: %s, %s]=],
["OnlyInstance"] = "Nur Instanzergebnisse anzeigen",
["OtherSex"] = "Anderes Geschlecht",
["RAIDSIZE"] = "Raidgröße: %d Personen",
["RAKSHA_CHEST_NOTE"] = "Kistenverteilung stimmt nur für Diamant!",
["Rarity"] = "+ Seltenheit:",
["Rune"] = "Rune %d:",
["SearchBoss"] = "Nach Bossen suchen",
["SearchInstance"] = "Nach Instanzen suchen",
["SearchItem"] = "Nach Items suchen",
["SearchList"] = "SuFu",
["SearchMinLength"] = [=[Suchbegriff muss aus mindestens %d Buchstaben bestehen!
Leerzeichen werden nicht gezählt!]=],
["SearchTreasure"] = "Nach Schätzen suchen",
["ShowBoss"] = "Zeige aktuelles Ziel",
["ShowInDB"] = "In der rom-welten.de Datenbank anzeigen",
["ShowInDL"] = "In Dungeon Loots anzeigen",
["ShowInstance"] = "Zeige aktuelle Zone",
["StartPlus"] = "GO!",
["Stat"] = "Stat %d:",
["TabTier"] = "+/Grad",
["TreasureList"] = "Schatzliste",
["UseDLBossPoi"] = "Zeige Dungeon Loot Boss Positionen",
["UseDLInstancePoi"] = "Zeige Dungeon Loot Instanzportale",
["UseDLPoi"] = "DL Pois benutzen",
["Version"] = "%s: Version %s",
["WorldmapButton"] = "DL-Einstellungen",
}
