-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/dungeonloots/localization/
--]]

return
{
["Boss_TT"] = "Boss %d: %s (%d)",
["Boss2_TT"] = "Loots -> %s (%d)",
["BossInstance"] = "Assign Bosses to Instances",
["BossList"] = "Boss List",
["ChangeSortOrder"] = "change sort order",
["HideWoWMapTeleport"] = "Hide WoWMap transportpoints",
["HideWoWMapZone"] = "Hide WoWMap Zoneportals",
["instance_memsmsg"] = "There are %s %s in this instance.",
["instance_memswarning"] = "%s %s too much!",
["InstanceList"] = "Instance List",
["InstanceOrder"] = "Order by %s",
["ItemList"] = "Item List",
["Itemplus"] = "Item +:",
["MoreButton"] = "More",
["NPCTT"] = [=[HP: %s
Atk: %s, %s
Def: %s, %s
CritRes: %s, %s]=],
["OnlyInstance"] = "Show  only Instance results",
["OtherSex"] = "Other Sex",
["RAIDSIZE"] = "Raid size: %d Persons",
["RAKSHA_CHEST_NOTE"] = "The distribution of the boxes are only for temple diamond correct!",
["Rarity"] = "+ Rarity:",
["Rune"] = "Rune %d:",
["SearchBoss"] = "Search for Bosses",
["SearchInstance"] = "Search for Instance",
["SearchItem"] = "Search for Items",
["SearchList"] = "Search List",
["SearchMinLength"] = [=[Your search criterion has to be at least %d letters!
Space wouldn´t be count!]=],
["SearchTreasure"] = "Search for Treasure",
["ShowBoss"] = "Show Current Target",
["ShowInDB"] = "Show in rom-welten.de database",
["ShowInDL"] = "Show in Dungeon Loots",
["ShowInstance"] = "Show Current Zone",
["StartPlus"] = "GO!",
["Stat"] = "Stat %d:",
["TabTier"] = "+/Tier",
["TreasureList"] = "Treasure List",
["UseDLBossPoi"] = "Show Dungeon Loot Boss Positions",
["UseDLInstancePoi"] = "Show Dungeon Loot Instance portals",
["UseDLPoi"] = "Use DL Pois",
["Version"] = "%s: Version %s",
["WorldmapButton"] = "DL-Options",
}
