-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/dungeonloots/localization/
--]]

return
{
["Boss_TT"] = "Boss",
["Boss2_TT"] = "Loteado -> %s (%d)",
["BossInstance"] = "Asignar Jefes de Instancias",
["BossList"] = "Lista de jefes",
["HideWoWMapTeleport"] = "Ocultar Transportes WoWMap",
["HideWoWMapZone"] = "Ocultar Portales WoWMap",
["instance_memsmsg"] = "Hay %s %s en esta instancia.",
["instance_memswarning"] = "%s %s demasiado!",
["InstanceList"] = "Lista de Instancias",
["ItemList"] = "Lista de Items",
["Itemplus"] = "Objeto +:",
["MoreButton"] = "Más",
["NPCTT"] = [=[HP: %s
Ataq: %s, %s
Def: %s, %s
ResCrit: %s, %s]=],
["OnlyInstance"] = "Mostrar sólo resultados de Instancia",
["OtherSex"] = "Otro sexo",
["RAIDSIZE"] = "Tamaño de Raid: %d Jugadores",
["RAKSHA_CHEST_NOTE"] = "La distribución de las cajas sólo para templo diamante!",
["Rarity"] = "+ Rareza:",
["Rune"] = "Runa %d:",
["SearchBoss"] = "Buscar por Bosses",
["SearchInstance"] = "Buscar por Instancia",
["SearchItem"] = "Buscar por Items",
["SearchList"] = "Lista de búsquedas",
["SearchMinLength"] = [=[Tu criterio de busqueda debe ser de al menos %d letras!
Los espacios no cuentan!]=],
["ShowBoss"] = "Mostrar Objetivo Actual",
["ShowInDB"] = "Mostrar en la database rom-welten.de",
["ShowInDL"] = "Mostrar en Dungeon Loots",
["ShowInstance"] = "Mostrar Zona Actual",
["StartPlus"] = "¡YA!",
["Stat"] = "Estad. %d:",
["TabTier"] = "+/Nivel",
["UseDLBossPoi"] = "Mostrar Posición de Boses DL",
["UseDLInstancePoi"] = "Mostrar Portal de instancia DL",
["UseDLPoi"] = "Usar Marcadores DL",
["Version"] = "%s: Versión %s",
["WorldmapButton"] = "DL-Opciones",
}
