-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/dungeonloots/localization/
--]]

return
{
["Boss_TT"] = "Boss %d: %s (%d)",
["Boss2_TT"] = "Łup -> %s (%d)",
["BossInstance"] = "Przypisz bosy do instancji",
["BossList"] = "Lista bosów",
["HideWoWMapTeleport"] = "Ukryj punkty transportowe WoWMap",
["HideWoWMapZone"] = "Ukryj portale stref WoWMap",
["instance_memsmsg"] = "W tej instancji jest %s %s.",
["instance_memswarning"] = "%s %s za dużo!",
["InstanceList"] = "Lista instancji",
["ItemList"] = "Lista przedmiotów",
["Itemplus"] = "Przedmiot +:",
["MoreButton"] = "Więcej",
["NPCTT"] = [=[PŻ: %s
Atak: %s, %s
Obr: %s, %s
OpórKryt: %s, %s]=],
["OnlyInstance"] = "Pokaż tylko z instancji",
["OtherSex"] = "Inna płeć",
["RAIDSIZE"] = "Rozmiar rajdu: %d osób",
["RAKSHA_CHEST_NOTE"] = "Podział skrzyń jest dostępny tylko dla poziomu diamentowego!",
["Rarity"] = "+ Rzadkość:",
["Rune"] = "Runa %d:",
["SearchBoss"] = "Szukaj bosów",
["SearchInstance"] = "Szukaj instancji",
["SearchItem"] = "Szukaj przedmiotów",
["SearchList"] = "Lista wyszukiwania",
["SearchMinLength"] = [=[Aby wyszukać, musisz podać przynajmniej %d znaków!
Spacja się nie liczy!]=],
["ShowBoss"] = "Pokaż bieżący cel",
["ShowInDB"] = "Pokaż w bazie danych rom-welten.de",
["ShowInDL"] = "Pokaż w Dungeon Loots",
["ShowInstance"] = "Pokaż bieżącą strefę",
["StartPlus"] = "OK!",
["Stat"] = "Statystyka %d:",
["TabTier"] = "+/Stopień",
["UseDLBossPoi"] = "Pokaż pozycje bossów Dungeon Loots",
["UseDLInstancePoi"] = "Pokaż portale instancji Dungeon Loots",
["UseDLPoi"] = "Używaj znaczników DL",
["Version"] = "%s: wersja %s",
["WorldmapButton"] = "DL: Ustawienia",
}
