-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/addonmanager/localization/
--]]
local lang={}
lang["AnchorFrame_Addition"] = [=[.
Strg halten um Andocken zu verhinden.]=]
lang["But_Enable"] = "Aktiv"
lang["But_Show"] = "Zeigen"
lang["description"] = "Verwaltet deine Addons... Du siehst es gerade an;)"
lang["SETTING_AutoHideMiniBar"] = "Automatisch ausblenden"
lang["SETTING_CharBasedEnable"] = "'Aktiv'-Flag Klassen abhängig"
lang["SETTING_LockMiniBar"] = "Fixiere Position"
lang["SETTING_MainCategory"] = "Haupt"
lang["SETTING_MiniCategory"] = "Mini-Addon Leiste"
lang["SETTING_MovePassiveToBack"] = "Sortiere passive Addons ans Ende"
lang["SETTING_ShowMiniBar"] = "Zeige Mini-Addon-Leiste"
lang["SETTING_ShowMiniBarBorder"] = "Zeige Rahmen"
lang["SETTING_ShowMinimapButton"] = "Zeige AddonManager Minimap button"
lang["SETTING_ShowOnlyNamesInMiniBar"] = "Zeige nur Namen"
lang["SETTING_ShowSlashCmdInsteadOfCat"] = "Zeige Slash Kommando anstelle der Kategorie"
lang["TAB_Addons"] = "Alle Addons"
lang["TAB_Setup"] = "Einstellungen"
lang["TIP_CMD"] = "Slash Kommando: "
lang["TIP_DEVS"] = "Entwickelt von "
lang["TIP_TRANSLATOR"] = "Übersetzung von "
lang.CAT = {
	Crafting = "Berufe",
	Development = "Entwicklung",
	Economy = "Wirtschaft",
	Information = "Information",
	Interface = "Interface",
	Inventory = "Inventory",
	Leveling = "Leveling",
	Map = "Karten",
	Other = "anderes",
	PvP = "PvP",
	Social = "Soziales",
}





return lang

