-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/addonmanager/localization/
--]]

local lang={}
lang["AnchorFrame_Addition"] = "Mantenga pressionado CTRL para suspender el acoplamiento." -- Needs review
lang["But_Enable"] = "Habilitado" -- Needs review
lang["But_Show"] = "Mostrar" -- Needs review
lang["description"] = "Gestione tus complementos... Los estás mirando ahora mismo ;)" -- Needs review
lang["SETTING_AutoHideMiniBar"] = "Auto-ocultar la Minibarra de complementos" -- Needs review
lang["SETTING_CharBasedEnable"] = "indicador 'Activo' basado en Clase" -- Needs review
lang["SETTING_LockMiniBar"] = "Bloquear posición de la Minibarra de complementos" -- Needs review
lang["SETTING_MainCategory"] = "Principal" -- Needs review
lang["SETTING_MiniCategory"] = "Minibarra de complementos" -- Needs review
lang["SETTING_MovePassiveToBack"] = "Enviar complementos pasivos al final de la lista" -- Needs review
lang["SETTING_ShowMiniBar"] = "Mostrar la Minibarra de complementos" -- Needs review
lang["SETTING_ShowMiniBarBorder"] = "Mostrar el borde de la Minibarra de complementos" -- Needs review
lang["SETTING_ShowMinimapButton"] = "Mostrar botón Gestor de complementos en el minimapa" -- Needs review
lang["SETTING_ShowOnlyNamesInMiniBar"] = "Mostrar sólo nombres en la Minibarra de Complementos" -- Needs review
lang["SETTING_ShowSlashCmdInsteadOfCat"] = "Mostrar comando (/) barra en vez de categoría" -- Needs review
lang["TAB_Addons"] = "Todos los complementos" -- Needs review
lang["TAB_Setup"] = "Configuraciones" -- Needs review
lang["TIP_CMD"] = "Comando barra (/)" -- Needs review
lang["TIP_DEVS"] = "Realizado por" -- Needs review
lang["TIP_TRANSLATOR"] = "Traducido por" -- Needs review
lang.CAT = {
	Crafting = "CAT", -- Needs review
	Development = "Desarrollo", -- Needs review
	Economy = "Economía", -- Needs review
	Information = "Información", -- Needs review
	Interface = "Interfaz", -- Needs review
	Inventory = "Inventario", -- Needs review
	Leveling = "Nivelación", -- Needs review
	Map = "Mapa", -- Needs review
	Other = "Otro(a)", -- Needs review
	PvP = "JvJ - Jugador contra Jugador", -- Needs review
	Social = "Social", -- Needs review
}


return lang
