-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/addonmanager/localization/
--]]

local lang={}
lang["AnchorFrame_Addition"] = "Maintenir CTRL pour déplacer."
lang["But_Enable"] = "Activé"
lang["But_Show"] = "Afficher"
lang["description"] = "Gérez vos Addons en toute simplicité ;) "
lang["SETTING_AutoHideMiniBar"] = "Cacher Automatiquement la Mini-barre"
lang["SETTING_LockMiniBar"] = "Verrouiller la Mini-Barre"
lang["SETTING_MainCategory"] = "Principale"
lang["SETTING_MiniCategory"] = "Mini-Barre"
lang["SETTING_MovePassiveToBack"] = "Trier les addons passifs à la fin de la liste."
lang["SETTING_ShowMiniBar"] = "Afficher la Mini-Barre"
lang["SETTING_ShowMiniBarBorder"] = "Afficher contour Mini-Barre"
lang["SETTING_ShowMinimapButton"] = "Afficher le bouton AddonManager sur la minimap"
lang["SETTING_ShowOnlyNamesInMiniBar"] = "Afficher uniquement les noms dans la Mini-Barre"
lang["SETTING_ShowSlashCmdInsteadOfCat"] = "Afficher commande slash au lieu des catégories"
lang["TAB_Addons"] = "Tous les Addons"
lang["TAB_Setup"] = "Configuration"
lang["TIP_CMD"] = "Commande slash:"
lang["TIP_DEVS"] = "Créer par"
lang["TIP_TRANSLATOR"] = "Traduit par:"
lang.CAT = {
	Crafting = "Crafting",
	Development = "Développement",
	Economy = "Economie",
	Information = "Information",
	Interface = "Interface",
	Inventory = "Inventaire",
	Leveling = "Leveling",
	Map = "Carte",
	Other = "Autre",
	PvP = "PvP",
	Social = "Social",
}


return lang
