-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/addonmanager/localization/
--]]

local lang={}
lang["AnchorFrame_Addition"] = "자동 붙이기를 멈추려면 CTRL 키를 누른 상태 유지"
lang["But_Enable"] = "활성화"
lang["But_Show"] = "보여주기"
lang["description"] = "당신의 애드온들을 관리하세요...You're looking at it right now ;)"
lang["SETTING_AutoHideMiniBar"] = "미니 애드온 바 자동 감추기"
lang["SETTING_LockMiniBar"] = "미니 애드온 바 위치 잠금"
lang["SETTING_MainCategory"] = "메인"
lang["SETTING_MiniCategory"] = "미니 애드온 바"
lang["SETTING_MovePassiveToBack"] = "패시브 애드온을 목록 뒤로 정리"
lang["SETTING_ShowMiniBar"] = "미니 애드온 바 보여주기"
lang["SETTING_ShowMiniBarBorder"] = "미니 애드온 바 테두리 보여주기"
lang["SETTING_ShowMinimapButton"] = "애드온 매니저 미니맵 아이콘 보여주기"
lang["SETTING_ShowOnlyNamesInMiniBar"] = "미니 애드온 바에 이름만 보여주기"
lang["SETTING_ShowSlashCmdInsteadOfCat"] = "종류별 분류대신 슬래쉬 명령어 보여주기"
lang["TAB_Addons"] = "모든 애드온들"
lang["TAB_Setup"] = "설정"
lang["TIP_CMD"] = "슬래쉬 명령어:"
lang["TIP_DEVS"] = "제작: " -- Needs review
lang["TIP_TRANSLATOR"] = "번역: " -- Needs review
lang.CAT = {
	Crafting = "제조",
	Development = "개발",
	Economy = "경제",
	Information = "정보",
	Interface = "화면",
	Inventory = "가방",
	Leveling = "레벨",
	Map = "지도",
	Other = "기타",
	PvP = "대전",
	Social = "사회",
}


return lang