-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/addonmanager/localization/
--]]

local lang={}
lang["AnchorFrame_Addition"] = [=[.
Przytrzymaj CTRL, aby zadokować.]=]
lang["But_Enable"] = "Włączony"
lang["But_Show"] = "Pokaż"
lang["description"] = "Zarządzaj swoimi addonami... Właśnie z niego korzystasz :)"
lang["SETTING_AutoHideMiniBar"] = "Automatyczne ukrywaj mini-pasek"
lang["SETTING_LockMiniBar"] = "Zablokuj mini-pasek"
lang["SETTING_MainCategory"] = "Główne"
lang["SETTING_MiniCategory"] = "Mini-pasek"
lang["SETTING_MovePassiveToBack"] = "Umieść pasywne addony na końcu listy"
lang["SETTING_ShowMiniBar"] = "Pokaż mini-pasek"
lang["SETTING_ShowMiniBarBorder"] = "Pokaż obwódkę mini-paska"
lang["SETTING_ShowMinimapButton"] = "Pokazuj przycisk AddonManager'a na minimapie"
lang["SETTING_ShowOnlyNamesInMiniBar"] = "Pokazuj na mini-pasku tylko nazwy"
lang["SETTING_ShowSlashCmdInsteadOfCat"] = "Pokazuj komendy zamiast kategorii"
lang["TAB_Addons"] = "Wszystkie addony"
lang["TAB_Setup"] = "Ustawienia"
lang["TIP_CMD"] = "Komenda: "
lang["TIP_DEVS"] = "Stworzone przez "
lang["TIP_TRANSLATOR"] = "Przetłumaczone przez "
lang.CAT = {
	Crafting = "Rzemiosło",
	Development = "Zarządzanie",
	Economy = "Ekonomia",
	Information = "Informacja",
	Interface = "Interfejs",
	Inventory = "Inwentarz",
	Leveling = "Poziomowanie",
	Map = "Mapa",
	Other = "Inne",
	PvP = "Walka",
	Social = "Społeczne",
}


return lang