-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/addonmanager/localization/
--]]

local lang={}
lang["AnchorFrame_Addition"] = "Зажми CTRL, чтобы претащить."
lang["But_Enable"] = "Включено"
lang["But_Show"] = "Показать"
lang["description"] = "Управляет твоими плагинами... Ты видишь это прямо сейчас ;)"
lang["SETTING_AutoHideMiniBar"] = "Автоскрытие минипанели"
lang["SETTING_LockMiniBar"] = "Зафиксировать минипанель"
lang["SETTING_MainCategory"] = "Главные"
lang["SETTING_MiniCategory"] = "Минипанель"
lang["SETTING_MovePassiveToBack"] = "Пассивные плагины в конце списка"
lang["SETTING_ShowMiniBar"] = "Минипанель"
lang["SETTING_ShowMiniBarBorder"] = "Граница минипанели"
lang["SETTING_ShowMinimapButton"] = "Кнопка на миникарте"
lang["SETTING_ShowOnlyNamesInMiniBar"] = "Только имена в минипанели"
lang["SETTING_ShowSlashCmdInsteadOfCat"] = "Слеш комманды вместо категории"
lang["TAB_Addons"] = "Все плагины"
lang["TAB_Setup"] = "Настройки"
lang["TIP_CMD"] = "Слеш комманда:"
lang["TIP_DEVS"] = "Сделано " -- Needs review
lang["TIP_TRANSLATOR"] = "Переведено " -- Needs review
lang.CAT = {
	Crafting = "Ремесло", -- Needs review
	Development = "Развитие",
	Economy = "Экономика",
	Information = "Информация",
	Interface = "Интерфейс",
	Inventory = "Рюкзак",
	Leveling = "Прогресс",
	Map = "Карта",
	Other = "Остальное",
	PvP = "ПвП",
	Social = "Общение", -- Needs review
}


return lang