-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/cleanchat/localization/
--]]

return
{
	Active = "Active",
	AddonLoaded = "Addon loaded: <ADDON>, type '<COMMAND>' to toggle GUI.",
	Description = "CleanChat is a tool to simplify customizing the chat and to get rid of annoying messages.",
	FiltersAdd = "Add new filter",
	FiltersCustom = "Custom filters",
	FiltersExplain = [=[You can use * (asterisk) as replacement.
For example for sentence 'John has car':
WILL MATCH 'John *', 'John * car', '* car',
but WON'T MATCH 'John * abc'.]=],
	FiltersFrame = "Messages filtering",
	FiltersOthers = "Others",
	FiltersPredefined = "Predefined filters",
	FiltersRemove = "Remove current filter",
}

