-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/cleanchat/localization/
--]]

return
{
	Active = "Active", -- Requires localization
	AddonLoaded = "Addon loaded: <ADDON>, type '<COMMAND>' to toggle GUI.", -- Requires localization
	Description = "CleanChat is a tool to simplify customizing the chat and to get rid of annoying messages.", -- Requires localization
	FiltersAdd = "Add new filter", -- Requires localization
	FiltersCustom = "Custom filters", -- Requires localization
	FiltersExplain = [=[You can use * (asterisk) as replacement.
For example for sentence 'John has car':
WILL MATCH 'John *', 'John * car', '* car',
but WON'T MATCH 'John * abc'.]=], -- Requires localization
	FiltersFrame = "Messages filtering", -- Requires localization
	FiltersOthers = "Others", -- Requires localization
	FiltersPredefined = "Predefined filters", -- Requires localization
	FiltersRemove = "Remove current filter", -- Requires localization
}

