-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/cleanchat/localization/
--]]

return
{
	Active = "Aktywne",
	AddonLoaded = "Dodatek załadowany: <ADDON>, wpisz '<COMMAND>', aby przełączyć widoczność GUI.",
	Description = "CleanChat to narzędzie ułatwiające dostosowanie czatu i pozbycie się niechcianych wiadomości.",
	FiltersAdd = "Dodaj nowy filtr",
	FiltersCustom = "Własne filtry",
	FiltersExplain = [=[Możesz użyć * (gwiazdka) jako zastępnika.
Przykładowo zdanie 'Ala ma kota':
DOPASUJE 'Ala *', 'Ala * kota', '* kota',
ale NIE DOPASUJE 'Ala * abc'.]=],
	FiltersFrame = "Filtrowanie wiadomości",
	FiltersOthers = "Inne",
	FiltersPredefined = "Gotowe filtry",
	FiltersRemove = "Usuń bieżący filtr",
}

