-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
{
	Menu = {
		Buildable = "Buildable Runes", -- Requires localization
		BuildList = "Build List", -- Requires localization
		Grade = "Grade ", -- Requires localization
		Needed = "Needed Runes", -- Requires localization
		Tier = "Rank <TIER> Runes", -- Requires localization
		UnrankedTier = "Unranked Runes", -- Requires localization
	},
	PrintOut = {
		Description = "Its a combination Guid for Runes.", -- Requires localization
		Say = "loaded! /rc to open RuneCraft", -- Requires localization
	},
	Runes = {
		AltMake = "Alternative recipe", -- Requires localization
		Deactive = "Deactivated", -- Requires localization
		NoMake = "Not produceable", -- Requires localization
		ShortAlt = "alt.", -- Requires localization
		TreasureHunt = "From mini-games", -- Requires localization
	},
}

