-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
{
	Menu = {
		Buildable = "Baubare Runen",
		BuildList = "Bau-Liste",
		Grade = "Grad ",
		Needed = "Benötigte Runen",
		Tier = "Rang <TIER> Runen",
		UnrankedTier = "Ranglose Runen",
	},
	PrintOut = {
		Description = "Es ist ein Kombinations Guid für Runen",
		Say = "geladen! /rc zum Öffnen des Menüs",
	},
	Runes = {
		AltMake = "alternatives Rezept",
		Deactive = "Deaktiviert",
		NoMake = "Nicht herstellbar",
		ShortAlt = "alt.",
		TreasureHunt = "In Minispiel Schatzsuche findbar",
	},
}

