-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
{
	Menu = {
		Buildable = "Buildable Runes",
		BuildList = "Build List",
		Grade = "Grade ",
		Needed = "Needed Runes",
		Tier = "Rank <TIER> Runes",
		UnrankedTier = "Unranked Runes",
	},
	PrintOut = {
		Description = "Its a combination Guid for Runes.",
		Say = "loaded! /rc to open RuneCraft",
	},
	Runes = {
		AltMake = "Alternative recipe",
		Deactive = "Deactivated",
		NoMake = "Not produceable",
		ShortAlt = "alt.",
		TreasureHunt = "From mini-games",
	},
}

