-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
{
	Menu = {
		Buildable = "Runas realizables",
		BuildList = "Lista de fabricación",
		Grade = "Grado",
		Needed = "Runas necesarias",
		Tier = "Runas de Rango <TIER> ",
		UnrankedTier = "Runas sin rango",
	},
	PrintOut = {
		Description = "Es una Guía de combinación de Runas.",
		Say = "Cargado! /rc para abrir RuneCraft",
	},
	Runes = {
		AltMake = "Receta alternativa",
		Deactive = "Desactivado",
		NoMake = "No realizable",
		ShortAlt = "alt.",
		TreasureHunt = "De minijuegos",
	},
}

