-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
{
	Menu = {
		Buildable = "Runes Craftables", -- Needs review
		BuildList = "Bau-Liste", -- Needs review
		Grade = "Rang", -- Needs review
		Needed = "Runes nécessaires", -- Needs review
		Tier = "Catégorie <TIER> Runes", -- Needs review
		UnrankedTier = "Unranked Runes", -- Requires localization
	},
	PrintOut = {
		Description = "Guide des combinaisons de Runes.", -- Needs review
		Say = "chargé! /rc pour ouvrir RuneCraft", -- Needs review
	},
	Runes = {
		AltMake = "Recette Alternative", -- Needs review
		Deactive = "Désactivée", -- Needs review
		NoMake = "Non-craftabe", -- Needs review
		ShortAlt = "alt.", -- Needs review
		TreasureHunt = "Provient des mini-jeux", -- Needs review
	},
}

