-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
{
	Menu = {
		Buildable = "Rune costruibili",
		BuildList = "Lista delle Combinazioni",
		Grade = "Grado",
		Needed = "Rune necessarie",
		Tier = "Rune Livello <TIER>",
		UnrankedTier = "Rune non classificate",
	},
	PrintOut = {
		Description = "È una combinazione di GUID per rune.",
		Say = "caricato! /rc per aprire RuneCraft",
	},
	Runes = {
		AltMake = "Ricetta alternativa",
		Deactive = "Disattivato",
		NoMake = "Non producibile",
		ShortAlt = "alt.",
		TreasureHunt = "Dai Mini Giochi",
	},
}

