-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
{
	Menu = {
		Buildable = "제작가능 룬", -- Needs review
		BuildList = "Build List", -- Requires localization
		Grade = "메뉴", -- Needs review
		Needed = "필요한 룬", -- Needs review
		Tier = "랭크 <TIER> 룬", -- Needs review
		UnrankedTier = "Unranked Runes", -- Requires localization
	},
	PrintOut = {
		Description = "룬 조합 가이드입니다.", -- Needs review
		Say = "로드되었습니다.", -- Needs review
	},
	Runes = {
		AltMake = "Alternative recipe", -- Requires localization
		Deactive = "비활성화 됨", -- Needs review
		NoMake = "생산 된 할 수 없습니다", -- Needs review
		ShortAlt = "alt.", -- Requires localization
		TreasureHunt = "미니 가지 게임에서", -- Needs review
	},
}

