-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
{
	Menu = {
		Buildable = "Możliwe do stworzenia",
		BuildList = "Lista tworzenia",
		Grade = "Stopień",
		Needed = "Potrzebne runy",
		Tier = "Runy rangi <TIER>",
		UnrankedTier = "Runy bez rangi",
	},
	PrintOut = {
		Description = "Poradnik do tworzenia run.",
		Say = "załadowany! Wpisz /rc, aby otworzyć RuneCraft",
	},
	Runes = {
		AltMake = "Inny sposób wytworzenia",
		Deactive = "Wyłączona",
		NoMake = "Niewykonalna",
		ShortAlt = "alt.",
		TreasureHunt = "Z minigierek",
	},
}

