-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
{
	Menu = {
		Buildable = "Создаваемые",
		BuildList = "Список построения", -- Needs review
		Grade = "Уровень",
		Needed = "Требуемые",
		Tier = "Ранг <TIER> Руны",
		UnrankedTier = "Руны без ранга", -- Needs review
	},
	PrintOut = {
		Description = "Справочник по комбинациям рун.",
		Say = "загружен!",
	},
	Runes = {
		AltMake = "Альтернативный способ",
		Deactive = "Отключенные.",
		NoMake = "Не крафтятся.",
		ShortAlt = "альт.",
		TreasureHunt = "Руны из малатин.",
	},
}

