-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
{
	Menu = {
		Buildable = "符文組合", -- Needs review
		BuildList = "Build List", -- Requires localization
		Grade = "等級", -- Needs review
		Needed = "所需要的符文", -- Needs review
		Tier = "  階層 <TIER> 符文", -- Needs review
		UnrankedTier = "Unranked Runes", -- Requires localization
	},
	PrintOut = {
		Description = "這是一個符文組合公式工具.", -- Needs review
		Say = "請輸入 /rc 打開工具", -- Needs review
	},
	Runes = {
		AltMake = "特殊合成公式", -- Needs review
		Deactive = "未開放合成", -- Needs review
		NoMake = "未開放", -- Needs review
		ShortAlt = "特", -- Needs review
		TreasureHunt = "舊版資料", -- Needs review
	},
}

