return {
"icons/eq_finger- 09",
"icons/eq_finger- 091",
"icons/eq_finger- 092",
"icons/eq_finger- 09_1",
"icons/eq_finger- 09_2",
"icons/eq_finger- 09_3",
"icons/eq_finger- 10",
"icons/eq_finger- 101",
"icons/eq_finger- 102",
"icons/eq_finger- 10_1",
"icons/eq_finger- 10_2",
"icons/eq_finger- 10_3",
"icons/eq_finger- 12",
"icons/eq_finger- 121",
"icons/eq_finger- 122",
"icons/eq_finger- 12_1",
"icons/eq_finger- 12_2",
"icons/eq_finger- 12_3",
"icons/eq_finger- 13_1",
"icons/eq_finger- 141",
"icons/eq_finger- 14_1",
"icons/eq_finger- 15_1",
"icons/eq_finger- 16_1",
"icons/eq_finger- 17_1",
"icons/eq_finger- 18_1",
"icons/eq_finger- 19_1",
"icons/eq_finger- 20_1",
"icons/eq_finger- 21_1",
"icons/eq_finger- 22_1",
"icons/eq_finger-01",
"icons/eq_finger-011",
"icons/eq_finger-012",
"icons/eq_finger-01_1",
"icons/eq_finger-01_2",
"icons/eq_finger-01_3",
"icons/eq_finger-02",
"icons/eq_finger-021",
"icons/eq_finger-022",
"icons/eq_finger-02_1",
"icons/eq_finger-02_2",
"icons/eq_finger-02_3",
"icons/eq_finger-03",
"icons/eq_finger-031",
"icons/eq_finger-032",
"icons/eq_finger-03_1",
"icons/eq_finger-03_2",
"icons/eq_finger-03_3",
"icons/eq_finger-04",
"icons/eq_finger-041",
"icons/eq_finger-042",
"icons/eq_finger-04_1",
"icons/eq_finger-04_2",
"icons/eq_finger-04_3",
"icons/eq_finger-05",
"icons/eq_finger-051",
"icons/eq_finger-052",
"icons/eq_finger-05_1",
"icons/eq_finger-05_2",
"icons/eq_finger-05_3",
"icons/eq_finger-06",
"icons/eq_finger-061",
"icons/eq_finger-062",
"icons/eq_finger-06_1",
"icons/eq_finger-06_2",
"icons/eq_finger-06_3",
"icons/eq_finger-07",
"icons/eq_finger-071",
"icons/eq_finger-072",
"icons/eq_finger-07_1",
"icons/eq_finger-07_2",
"icons/eq_finger-07_3",
"icons/eq_finger-08",
"icons/eq_finger-081",
"icons/eq_finger-082",
"icons/eq_finger-08_1",
"icons/eq_finger-08_2",
"icons/eq_finger-08_3",
"icons/eq_finger-11",
"icons/eq_finger-111",
"icons/eq_finger-112",
"icons/eq_finger-11_1",
"icons/eq_finger-11_2",
"icons/eq_finger-11_3",
"icons/eq_finger-13",
"icons/eq_finger-131",
"icons/eq_finger-132",
"icons/eq_finger-13_1",
"icons/eq_finger-13_2",
"icons/eq_finger-13_3",
"icons/eq_finger-14",
"icons/eq_finger-141",
"icons/eq_finger-142",
"icons/eq_finger-14_1",
"icons/eq_finger-14_2",
"icons/eq_finger-14_3",
"icons/eq_finger-14_4",
"icons/eq_finger_fate_01",
"icons/weapon/eq_finger-23_1",
"icons/weapon/item_common_ring01",
"icons/weapon/item_common_ring02",
"icons/weapon/item_common_ring03",
"icons/weapon/item_common_ring04",
"icons/weapon/item_common_ring05",
"icons/weapon/item_common_ring06",
"icons/weapon/item_common_ring07",
"icons/weapon/item_common_ring08",
"icons/weapon/item_common_ring09",
"icons/weapon/item_common_ring10",
"icons/weapon/item_eternal_ring",
"icons/weapon/quest_ring_01",
"icons/weapon/quest_ring_02",
"icons/weapon/quest_ring_03",
"icons/weapon/quest_ring_04",
"icons/weapon/quest_ring_05",
"icons/weapon/quest_ring_06",
"icons/weapon/quest_ring_07",
"icons/weapon/quest_ring_08",
"icons/weapon/quest_ring_09",
"icons/weapon/quest_ring_10",
"icons/jewelry/ring_01",
"icons/jewelry/ring_02",
"icons/jewelry/ring_03",
"icons/jewelry/ring_04",
"icons/jewelry/ring_05",
"icons/jewelry/ring_06",
"icons/jewelry/ring_07",
"icons/jewelry/ring_08",
"icons/jewelry/ring_09",
"icons/jewelry/ring_10",
"icons/jewelry/ring_11",
"icons/jewelry/ring_12",
"icons/jewelry/ring_13",
"icons/jewelry/ring_14",
"icons/jewelry/ring_15",
"icons/jewelry/ring_16",
"icons/jewelry/ring_17",
"icons/jewelry/ring_18",
"icons/jewelry/ring_19",
"icons/jewelry/ring_20",
"icons/jewelry/ring_21",
"icons/jewelry/ring_22",
"icons/jewelry/ring_23",
"icons/jewelry/ring_24",
"icons/jewelry/ring_25",
"icons/jewelry/ring_26",
"icons/jewelry/ring_27",
"icons/jewelry/ring_28",
"icons/jewelry/ring_29",
"icons/jewelry/ring_30",
"icons/jewelry/ring_31",
"icons/jewelry/ring_32",
"icons/jewelry/ring_33",
"icons/jewelry/ring_34",
"icons/jewelry/ring_35",
}
