return {
"icons/ammo1",
"icons/ammo2",
"icons/ammo3",
"icons/amulet_item_01",
"icons/amulet_item_02",
"icons/amulet_item_03",
"icons/amulet_item_04",
"icons/amulet_item_05",
"icons/backpack_pet00",
"icons/bag01",
"icons/bag02",
"icons/bag03",
"icons/bast_01",
"icons/bast_02",
"icons/bast_03",
"icons/bast_04",
"icons/bast_05",
"icons/bast_06",
"icons/bast_07",
"icons/bast_08",
"icons/battlecoin",
"icons/battlecoin_blue",
"icons/battlecoin_green",
"icons/battlecoin_red",
"icons/battlecoin_yellow",
"icons/biodin_shop_money",
"icons/box_gift_001",
"icons/box_gift_002",
"icons/box_gift_003",
"icons/box_gift_004",
"icons/box_gift_005",
"icons/cant speak",
"icons/chest_001",
"icons/chest_002",
"icons/chest_003",
"icons/chest_004",
"icons/chest_005",
"icons/chest_006",
"icons/coin_01",
"icons/coin_02",
"icons/coin_03",
"icons/coin_04",
"icons/crocodile_green01_01",
"icons/crocodile_green01_blu",
"icons/crocodile_green01_gre",
"icons/crocodile_green01_ora",
"icons/crystal_01",
"icons/cyclops_mh_creative_icon001",
"icons/cyclops_mh_msi_icon002",
"icons/del_subjob",
"icons/diamond_01",
"icons/diamond_02",
"icons/dismount",
"icons/duties_book_01",
"icons/duties_book_02",
"icons/duties_statue_01",
"icons/duties_stone_01",
"icons/duties_stone_02",
"icons/duties_stone_03",
"icons/duties_stone_04",
"icons/duties_stone_05",
"icons/duties_stone_06",
"icons/eq_insignia_fate_01",
"icons/eq_insignia_luck_01",
"icons/face_001",
"icons/firework",
"icons/fusion_stone001",
"icons/fusion_stone002",
"icons/gbottle",
"icons/geq",
"icons/gshield",
"icons/gwp",
"icons/house_energy",
"icons/im_ball01",
"icons/im_ball02",
"icons/im_ball03",
"icons/im_ball04",
"icons/im_ball05",
"icons/im_ball06",
"icons/im_ball07",
"icons/im_ball08",
"icons/internet_cafe_buff",
"icons/internet_cafe_buff2",
"icons/internet_cafe_buff3",
"icons/item_moncard",
"icons/item_orz_card",
"icons/item_pos_001",
"icons/item_pos_002",
"icons/item_pos_003",
"icons/item_pos_004",
"icons/item_pos_005",
"icons/item_pos_006",
"icons/item_pos_007",
"icons/item_pos_008",
"icons/item_pos_009",
"icons/item_pos_010",
"icons/item_pos_011",
"icons/item_pos_012",
"icons/item_pos_013",
"icons/item_pos_014",
"icons/item_pos_015",
"icons/item_pos_016",
"icons/item_treasure01",
"icons/item_treasure02",
"icons/item_treasure03",
"icons/mala2_01",
"icons/mala2_010",
"icons/mala2_011",
"icons/mala2_02",
"icons/mala2_03",
"icons/mala2_04",
"icons/mala2_05",
"icons/mala2_06",
"icons/mala2_07",
"icons/mala2_08",
"icons/mala2_09",
"icons/mana stone01",
"icons/mana stone02",
"icons/mana stone03",
"icons/mana stone04",
"icons/mana stone05",
"icons/mana stone06",
"icons/mana stone07",
"icons/mana stone08",
"icons/mana stone09",
"icons/mana stone10",
"icons/money_boss",
"icons/money_monster",
"icons/navigation_person_weapon",
"icons/pack_001",
"icons/pack_002",
"icons/pack_003",
"icons/pack_004",
"icons/pack_005",
"icons/pack_006",
"icons/pack_007",
"icons/pet_drion",
"icons/pet_skill_attack",
"icons/pet_skill_follow",
"icons/pet_skill_protect",
"icons/pet_skill_stop",
"icons/pet_skill_stop_attack",
"icons/power stone01",
"icons/power stone02",
"icons/power stone03",
"icons/power stone04",
"icons/power stone05",
"icons/power stone06",
"icons/power stone07",
"icons/power stone08",
"icons/power stone09",
"icons/power stone10",
"icons/race_01",
"icons/race_010",
"icons/race_02",
"icons/race_03",
"icons/race_04",
"icons/race_05",
"icons/race_06",
"icons/race_07",
"icons/race_08",
"icons/race_09",
"icons/reci_alc_001",
"icons/reci_arm_001",
"icons/reci_car_001",
"icons/reci_coo_001",
"icons/reci_smi_001",
"icons/reci_tai_001",
"icons/relation_01",
"icons/relation_02",
"icons/relation_03",
"icons/relation_04",
"icons/relationship_skill_01",
"icons/relationship_skill_02",
"icons/relationship_skill_03",
"icons/relationship_skill_04",
"icons/relationship_skill_05",
"icons/relationship_skill_06",
"icons/relationship_skill_07",
"icons/ruby_01",
"icons/runewaker_logo",
"icons/runewaker_logo_new",
"icons/shop box",
"icons/shop key",
"icons/shop_shield_m005_mall005",
"icons/shop_use_backpack_001",
"icons/shop_use_backpack_002",
"icons/shop_use_backpack_003",
"icons/shop_use_backpack_004",
"icons/shop_use_backpack_005",
"icons/shop_use_backpack_006",
"icons/shop_use_backpack_007",
"icons/shop_use_backpack_008",
"icons/shop_use_backpack_009",
"icons/shop_use_backpack_010",
"icons/shop_use_backpack_011",
"icons/shop_use_backpack_012",
"icons/shop_use_backpack_013",
"icons/shop_use_backpack_014",
"icons/shop_use_backpack_015",
"icons/shop_use_backpack_016",
"icons/shop_use_backpack_017",
"icons/skill _pk01",
"icons/skill book 001",
"icons/skill book 002",
"icons/skill book 003",
"icons/skill book 004",
"icons/skill book 005",
"icons/skill_att",
"icons/skill_buff05",
"icons/skill_buff07_01",
"icons/skill_buff07_02",
"icons/skill_buff08",
"icons/skill_buff09_pk stop",
"icons/skill_convict",
"icons/skill_deathblade",
"icons/skill_felbpower",
"icons/skill_firebrand01",
"icons/skill_firebrand02",
"icons/skill_flint",
"icons/skill_fuel_hand",
"icons/skill_house_use_001",
"icons/skill_mag_powerup",
"icons/skill_mag_skill_001",
"icons/skill_mag_skill_002",
"icons/skill_pkhunt001",
"icons/skill_pri_skill_001",
"icons/skill_pri_skill_002",
"icons/skill_ran_skill_001",
"icons/skill_ran_skill_002",
"icons/skill_run_skill_001",
"icons/skill_run_skill_002",
"icons/skill_stableriding",
"icons/skill_thi_skill_001",
"icons/skill_thi_skill_002",
"icons/skill_unlearn",
"icons/skill_war_skill_001",
"icons/skill_war_skill_002",
"icons/story_01",
"icons/story_02",
"icons/story_03",
"icons/story_04",
"icons/story_05",
"icons/story_06",
"icons/story_07",
"icons/story_08",
"icons/story_09",
"icons/story_10",
"icons/story_11",
"icons/story_12",
"icons/story_13",
"icons/story_14",
"icons/sys_decompose",
"icons/sys_haircolor",
"icons/sys_hairstyle",
"icons/sys_home01",
"icons/sys_home02",
"icons/sys_home03",
"icons/sys_home04",
"icons/sys_skincolor",
"icons/sys_transfer",
"icons/test_icons_01",
"icons/test_icons_02",
"icons/test_icons_03",
"icons/test_icons_04",
"icons/test_icons_05",
"icons/test_icons_06",
"icons/test_icons_07",
"icons/test_icons_08",
"icons/test_icons_09",
"icons/test_icons_10",
"icons/to buy",
"icons/weapon/wp_throwing_axe_01",
"icons/weapon/wp_throwing_knife_01",
"icons/weapon/wp_throwing_knife_02",
"icons/quest_dragon_tattoo_03",
"icons/quest_dragon_tattoo_04",
}
