return {
"icons/weapon/weapon_blade_turkishflag",
"icons/weapon/wp_blade-m017_algeria-flag",
"icons/weapon/wp_blade-m017_argentina-flag",
"icons/weapon/wp_blade-m017_australia-flag",
"icons/weapon/wp_blade-m017_bahrain-flag",
"icons/weapon/wp_blade-m017_belize-flag",
"icons/weapon/wp_blade-m017_black-white",
"icons/weapon/wp_blade-m017_bolivia-flag",
"icons/weapon/wp_blade-m017_brazil-flag",
"icons/weapon/wp_blade-m017_cameroons-flag",
"icons/weapon/wp_blade-m017_chile-flag",
"icons/weapon/wp_blade-m017_colombia-flag",
"icons/weapon/wp_blade-m017_costa rica-flag",
"icons/weapon/wp_blade-m017_denmark-flag",
"icons/weapon/wp_blade-m017_ecuador-flag",
"icons/weapon/wp_blade-m017_egypt-flag",
"icons/weapon/wp_blade-m017_el salvador-flag",
"icons/weapon/wp_blade-m017_england-flag",
"icons/weapon/wp_blade-m017_france-flag",
"icons/weapon/wp_blade-m017_germany-flag",
"icons/weapon/wp_blade-m017_ghana-flag",
"icons/weapon/wp_blade-m017_greece-flag",
"icons/weapon/wp_blade-m017_green-white",
"icons/weapon/wp_blade-m017_guatemala-flag",
"icons/weapon/wp_blade-m017_honduran-flag",
"icons/weapon/wp_blade-m017_iran-flag",
"icons/weapon/wp_blade-m017_iraq-flag",
"icons/weapon/wp_blade-m017_italy-flag",
"icons/weapon/wp_blade-m017_ivory coast-flag",
"icons/weapon/wp_blade-m017_japan-flag",
"icons/weapon/wp_blade-m017_jordan-flag",
"icons/weapon/wp_blade-m017_kuwait-flag",
"icons/weapon/wp_blade-m017_lebanon-flag",
"icons/weapon/wp_blade-m017_libya-2-flag",
"icons/weapon/wp_blade-m017_libya-flag",
"icons/weapon/wp_blade-m017_mexico-flag",
"icons/weapon/wp_blade-m017_morocco-flag",
"icons/weapon/wp_blade-m017_netherlands-flag",
"icons/weapon/wp_blade-m017_new zealand-flag",
"icons/weapon/wp_blade-m017_nicaragua-flag",
"icons/weapon/wp_blade-m017_nigeria-flag",
"icons/weapon/wp_blade-m017_north korea-flag",
"icons/weapon/wp_blade-m017_oman-flag",
"icons/weapon/wp_blade-m017_palestine-flag",
"icons/weapon/wp_blade-m017_panama-flag",
"icons/weapon/wp_blade-m017_paraguay-flag",
"icons/weapon/wp_blade-m017_peru-flag",
"icons/weapon/wp_blade-m017_philippines-flag",
"icons/weapon/wp_blade-m017_poland-flag",
"icons/weapon/wp_blade-m017_portugal-flag",
"icons/weapon/wp_blade-m017_qatar-flag",
"icons/weapon/wp_blade-m017_red-white",
"icons/weapon/wp_blade-m017_russia-flag",
"icons/weapon/wp_blade-m017_saudi arabia-flag",
"icons/weapon/wp_blade-m017_scarlet-blue",
"icons/weapon/wp_blade-m017_serbia-flag",
"icons/weapon/wp_blade-m017_slovakia-flag",
"icons/weapon/wp_blade-m017_slovenia-flag",
"icons/weapon/wp_blade-m017_south africa-flag",
"icons/weapon/wp_blade-m017_south korea-flag",
"icons/weapon/wp_blade-m017_spain-flag",
"icons/weapon/wp_blade-m017_sudan-flag",
"icons/weapon/wp_blade-m017_switzerland-flag",
"icons/weapon/wp_blade-m017_syria-flag",
"icons/weapon/wp_blade-m017_taiwan-flag",
"icons/weapon/wp_blade-m017_thailand-flag",
"icons/weapon/wp_blade-m017_the_united_arab_emirates-flag",
"icons/weapon/wp_blade-m017_tunisia-flag",
"icons/weapon/wp_blade-m017_uruguay-flag",
"icons/weapon/wp_blade-m017_usa-flag",
"icons/weapon/wp_blade-m017_venezuela-flag",
"icons/weapon/wp_blade-m017_yellow-navyblue",
"icons/weapon/wp_blade-m017_yellow-red",
"icons/weapon/eq_blade-m017_belgium-flag",
"icons/weapon/eq_blade-m017_croatia-flag",
"icons/weapon/eq_blade-m017_herzegovina-flag",
}
