g_MinimapDate = {
	[7] = true,
	[1] = true,
	[2] = true,
	[8] = true,
	[9] = true,
	[5] = true,
	[10] = true,
	[11] = true,
	[21] = true,
	[6] = true,
	["ZoomIndex"] = 1,
	[3] = true,
}
g_UIPanelAnchorFrameOptions = {
	["RaidPartyOptionFrame6"] = {
		["y"] = 212,
		["x"] = 152,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyOptionFrame1",
	},
	["RaidFocusFrame"] = {
		["y"] = -304,
		["x"] = -157,
		["point"] = "BOTTOMRIGHT",
		["relativePoint"] = "BOTTOMRIGHT",
		["relativeTo"] = "UIParent",
	},
	["SimpleDamageLogFrameDmgOut"] = {
		["y"] = 176,
		["x"] = -204.24609375,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["MinimapBeautyStudioButton"] = {
		["y"] = -11.979999542236,
		["x"] = -79.09700012207,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["PEFs_Item7_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item7",
	},
	["RaidPartyFrame6"] = {
		["y"] = 152,
		["x"] = 140,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyFrame1",
	},
	["PEFs_Item5_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item5",
	},
	["ChatFrameChannelChangeResizeButton"] = {
		["y"] = 2,
		["x"] = 150,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "ChatFrameChannelChange",
	},
	["AdvQuestBookMiniMapShareButton"] = {
		["y"] = 204,
		["x"] = -4,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["QuestAnnouncerMinimapButton"] = {
		["y"] = 180,
		["x"] = -96,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["MinimapFrameBattleGroundButton"] = {
		["y"] = 83,
		["x"] = -176.24609375,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["MainActionBarFrame"] = {
		["y"] = -46,
		["x"] = -96,
		["point"] = "BOTTOMRIGHT",
		["relativePoint"] = "BOTTOMRIGHT",
		["relativeTo"] = "UIParent",
	},
	["RaidPartyFrame5"] = {
		["y"] = 0,
		["x"] = 140,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyFrame1",
	},
	["PetBookFrameButton"] = {
		["y"] = 98,
		["x"] = 138,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "UIParent",
	},
	["AutoAI_Button"] = {
		["y"] = 180,
		["x"] = -120,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["SendVC_Button"] = {
		["y"] = 180,
		["x"] = -48,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["UI_Stellar_Floating_Status"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOP",
		["relativePoint"] = "TOP",
		["relativeTo"] = "UIParent",
	},
	["LootIt_MinimapButton"] = {
		["y"] = 107,
		["x"] = -175.24609375,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["RaidPartyFrame3"] = {
		["y"] = 0,
		["x"] = 70,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyFrame1",
	},
	["LeftActionBarFrame"] = {
		["y"] = -122,
		["x"] = -96,
		["point"] = "BOTTOMRIGHT",
		["relativePoint"] = "BOTTOMRIGHT",
		["relativeTo"] = "UIParent",
	},
	["MinimapFrameTopupButton"] = {
		["y"] = 132,
		["x"] = -175.24609375,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["CastingBarFrame"] = {
		["y"] = -120,
		["x"] = 0,
		["point"] = "BOTTOM",
		["relativePoint"] = "BOTTOM",
		["relativeTo"] = "UIParent",
	},
	["PEFs_Item1_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item1",
	},
	["AutoBG_Button"] = {
		["y"] = 180,
		["x"] = -72,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["MinimapNpcTrackButton"] = {
		["y"] = -39.85599899292,
		["x"] = -69.363998413086,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["TheQuestTrackerBar"] = {
		["y"] = 189,
		["x"] = -342,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["AddonManagerMiniFrame"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["IMBF_Talisman0Slot"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOP",
		["relativePoint"] = "TOP",
		["relativeTo"] = "ItemMallBufferFrame",
	},
	["LootIt_History_Move"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "LootIt_History",
	},
	["RaidFocusFrameAnchorFrame"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOP",
		["relativePoint"] = "TOP",
		["relativeTo"] = "RaidFocusFrame",
	},
	["RaidPartyOptionFrame3"] = {
		["y"] = 106,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyOptionFrame1",
	},
	["RightActionBarFrame"] = {
		["y"] = 68,
		["x"] = 0,
		["point"] = "RIGHT",
		["relativePoint"] = "RIGHT",
		["relativeTo"] = "UIParent",
	},
	["PEFs_Item8_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item8",
	},
	["RaidPartyFrame1AnchorFrame"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOP",
		["relativePoint"] = "TOP",
		["relativeTo"] = "RaidPartyFrame1",
	},
	["EventHelper_Minimap"] = {
		["y"] = 180,
		["x"] = -144,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["PlayerFrameWorldBattleGroundButton"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "BOTTOM",
		["relativePoint"] = "TOP",
		["relativeTo"] = "PlayerFramePetButton",
	},
	["PEFs_Item6_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item6",
	},
	["RaidPartyOptionFrame5"] = {
		["y"] = 212,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyOptionFrame1",
	},
	["IV_MinimapButton"] = {
		["y"] = 180,
		["x"] = 0,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["MinimapFrameRestoreUIButton"] = {
		["y"] = 24.409999847412,
		["x"] = 76.180000305176,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["SettingsLoader_Button"] = {
		["y"] = 35,
		["x"] = -176.24609375,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["MinimapFrameBugGartherButton"] = {
		["y"] = 156,
		["x"] = 0,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["AddonManagerMinimapButton"] = {
		["y"] = 59,
		["x"] = -176.24609375,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["DL_Minimap"] = {
		["y"] = 180,
		["x"] = -24,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["PEFs_Item2_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item2",
	},
	["PlayerFramePartyBoardButton"] = {
		["y"] = 30,
		["x"] = 308,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "UIParent",
	},
	["SimpleDamageLogFrameDmgIn"] = {
		["y"] = 178,
		["x"] = -304.24609375,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["PlayerFramePetButton"] = {
		["y"] = 95,
		["x"] = 113,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "UIParent",
	},
	["RaidPartyFrame1"] = {
		["y"] = 120,
		["x"] = 15,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "UIParent",
	},
	["QH_QuestTracker"] = {
		["y"] = -62,
		["x"] = -172.91149902344,
		["point"] = "RIGHT",
		["relativePoint"] = "RIGHT",
		["relativeTo"] = "UIParent",
	},
	["RestackButton"] = {
		["y"] = 180,
		["x"] = -175.24609375,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["GameTooltipHyperLink"] = {
		["y"] = -60,
		["x"] = -65,
		["point"] = "BOTTOMRIGHT",
		["relativePoint"] = "BOTTOMRIGHT",
		["relativeTo"] = "UIParent",
	},
	["RaidPartyOptionFrame4"] = {
		["y"] = 106,
		["x"] = 152,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyOptionFrame1",
	},
	["RaidPartyOptionFrame6AnchorFrame"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOP",
		["relativePoint"] = "TOP",
		["relativeTo"] = "RaidPartyOptionFrame6",
	},
	["RaidPartyOptionFrame3AnchorFrame"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOP",
		["relativePoint"] = "TOP",
		["relativeTo"] = "RaidPartyOptionFrame3",
	},
	["RaidPartyOptionFrame5AnchorFrame"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOP",
		["relativePoint"] = "TOP",
		["relativeTo"] = "RaidPartyOptionFrame5",
	},
	["RaidPartyFrame4"] = {
		["y"] = 152,
		["x"] = 70,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyFrame1",
	},
	["MinimapFrameStoreButton"] = {
		["y"] = 19.108999252319,
		["x"] = -77.68399810791,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["BottomActionBarFrame"] = {
		["y"] = -84,
		["x"] = -96,
		["point"] = "BOTTOMRIGHT",
		["relativePoint"] = "BOTTOMRIGHT",
		["relativeTo"] = "UIParent",
	},
	["PEFs_Item3_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item3",
	},
	["MinimapFrameBulletinButton"] = {
		["y"] = -61.729000091553,
		["x"] = -50.880001068115,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["PEFs_Item4_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item4",
	},
	["UMMNewMailButton"] = {
		["y"] = 0,
		["x"] = -40,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "MinimapViewFrame",
	},
	["PEFs_Item9_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item9",
	},
	["RaidPartyOptionFrame4AnchorFrame"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOP",
		["relativePoint"] = "TOP",
		["relativeTo"] = "RaidPartyOptionFrame4",
	},
	["RaidPartyOptionFrame2AnchorFrame"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOP",
		["relativePoint"] = "TOP",
		["relativeTo"] = "RaidPartyOptionFrame2",
	},
	["RaidPartyOptionFrame1AnchorFrame"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOP",
		["relativePoint"] = "TOP",
		["relativeTo"] = "RaidPartyOptionFrame1",
	},
	["PEFs_Item10_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item10",
	},
	["MinimapFrameQuestTrackButton"] = {
		["y"] = 45.284999847412,
		["x"] = -65.947998046875,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["RaidPartyFrame2"] = {
		["y"] = 152,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyFrame1",
	},
	["DAS_Toggle"] = {
		["y"] = 156,
		["x"] = -175.24609375,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["MinimapFrameOptionButton"] = {
		["y"] = 11,
		["x"] = -176.24609375,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["RaidPartyOptionFrame2"] = {
		["y"] = 0,
		["x"] = 152,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyOptionFrame1",
	},
}
g_WorldMapConfig = {
	["showNewQuest"] = true,
	["showTrustQuest"] = true,
	["showParty"] = 1,
	["showUnfinishQuest"] = false,
	["size"] = 90,
	["hideQuestTrackFrame"] = false,
	["showFinishedQuest"] = true,
	["showTrackNpc"] = 1,
	["showQuestNpc"] = 1,
	["hideLowQuest"] = 1,
}