--[[ ä

	Name: Advanced Questbook
	By: Crypton

]]
if (AQB_CLASSES == nil) then
	AQB_CLASSES = {
		["AQB_PRIEST"] = TEXT("SYS_CLASSNAME_AUGUR"),
		["AQB_DRUID"] = TEXT("SYS_CLASSNAME_DRUID"),
		["AQB_GM"] = TEXT("SYS_CLASSNAME_GM"),
		["AQB_KNIGHT"] = TEXT("SYS_CLASSNAME_KNIGHT"),
		["AQB_MAGE"] = TEXT("SYS_CLASSNAME_MAGE"),
		["AQB_SCOUT"] = TEXT("SYS_CLASSNAME_RANGER"),
		["AQB_RUNEDANCER"] = TEXT("SYS_CLASSNAME_RUNEDANCER"),
		["AQB_ROGUE"] = TEXT("SYS_CLASSNAME_THIEF"),
		["AQB_WARRIOR"] = TEXT("SYS_CLASSNAME_WARRIOR"),
		["AQB_WARDEN"] = TEXT("SYS_CLASSNAME_WARDEN"),
	};
end
