return {
	{"skill_priest.lua",			"Skills: Priest",				"10000"},
	{"skill_knight.lua",			"Skills: Knight",				"10001"},
	{"skill_thief.lua",				"Skills: Thief",				"10002"},
	{"skill_ranger.lua",			"Skills: Ranger",				"10003"},
	{"skill_warrior.lua",			"Skills: Warrior",				"10004"},
	{"skill_mage.lua",				"Skills: Mage",					"10005"},
	{"skill_druid.lua",				"Skills: Druid",				"10006"},
	{"skill_warden.lua",			"Skills: Warden",				"10007"},
	{"skill_champion.lua",			"Skills: Champion",				"10008"},
	{"skill_warlock.lua",			"Skills: Warlock",				"10009"},
	{"skill_sets.lua",				"Skills: Sets",					"10010"},
	{"skill_boss.lua",				"Skills: Boss",					"10011"},
	{"skill_dru.lua",				"Skills: unknown",				"10012"},
	{"skill_run.lua",				"Skills: unknown",				"10013"},
	{"equipment_belt.lua",			"Equipment: Belt",				"10100"},
	{"equipment_cape.lua",			"Equipment: Cape",				"10101"},
	{"equipment_ear.lua",			"Equipment: Ear",				"10102"},
	{"equipment_foot.lua",			"Equipment: Foot",				"10103"},
	{"equipment_hand.lua",			"Equipment: Hand",				"10104"},
	{"equipment_helm.lua",			"Equipment: Head",				"10105"},
	{"equipment_leg.lua",			"Equipment: Leg",				"10106"},
	{"equipment_neck.lua",			"Equipment: Neck",				"10107"},
	{"equipment_ring.lua",			"Equipment: Ring",				"10108"},
	{"equipment_shield.lua",		"Equipment: Shield",			"10109"},
	{"equipment_shoulder.lua",		"Equipment: Shoulder",			"10110"},
	{"equipment_talisman.lua",		"Equipment: Talisman",			"10111"},
	{"equipment_torso.lua",			"Equipment: Torso",				"10112"},
	{"equipment_wings.lua",			"Equipment: Wings",				"10113"},
	{"weapon_1h_axe.lua",			"Weapon: 1h Axe",				"10200"},
	{"weapon_1h_blade.lua",			"Weapon: 1h Blade",				"10201"},
	{"weapon_1h_dagger.lua",		"Weapon: 1h Dagger",			"10202"},
	{"weapon_1h_flags.lua",			"Weapon: 1h Flags",				"10203"},
	{"weapon_1h_hammer.lua",		"Weapon: 1h Hammer",			"10204"},
	{"weapon_1h_staff.lua",			"Weapon: 1h Staff",				"10205"},
	{"weapon_2h_axe.lua",			"Weapon: 2h Axe",				"10206"},
	{"weapon_2h_blade.lua",			"Weapon: 2h Blade",				"10207"},
	{"weapon_2h_bow.lua",			"Weapon: 2h Bow",				"10208"},
	{"weapon_2h_crossbow.lua",		"Weapon: 2h Crossbow",			"10209"},
	{"weapon_2h_hammer.lua",		"Weapon: 2h Hammer",			"10210"},
	{"weapon_2h_staff.lua",			"Weapon: 2h Staff",				"10211"},
	{"item_crafting.lua",			"Item: Crafting",				"10300"},
	{"item_flowerpot.lua",			"Item: Flowerpot",				"10301"},
	{"item_food.lua",				"Item: Food",					"10302"},
	{"item_potions.lua",			"Item: Potions",				"10303"},
	{"item_quests.lua",				"Item: Quests",					"10304"},
	{"item_pets_mounts.lua",		"Item: Pets/Mounts",			"10305"},
	{"cashshop.lua",				"Cashshop",						"10400"},
	{"emote.lua",					"Emote",						"10401"},
	{"festival.lua",				"Festival",						"10402"},
	{"furniture.lua",				"Furniture",					"10403"},
	{"map_zones.lua",				"Map Zones",					"10404"},
	{"numbers.lua",					"Numbers",						"10405"},
	{"siegewar.lua",				"Siegewar",						"10406"},
	{"phantom.lua",					"Mirrorworld",					"10407"},
	{"upgrade_plusstone.lua",		"Upgrade: Plusstone",			"10500"},
	{"upgrade_runes.lua",			"Upgrade: Runes",				"10501"},
	{"unsorted.lua",				"Miscellaneous",				"10600"},
	{"cus_transportbook.lua",		"Transportbook Icons",			"90000"},
}
